const grade7Questions = {
    EASY: {
        unit1: [
            { question: "Who was the first President of the United States?", choices: ["John Adams", "Thomas Jefferson", "George Washington", "Alexander Hamilton"], answer: 2, hint: "He set many precedents, including leaving after two terms.", dok: 1 },
            { question: "Which leader of the Federalist Party served as the first Secretary of the Treasury?", choices: ["James Madison", "Thomas Jefferson", "Aaron Burr", "Alexander Hamilton"], answer: 3, hint: "He is featured on the ten-dollar bill and championed the National Bank.", dok: 1 },
            { question: "What was the 1794 uprising of farmers protesting a federal tax called?", choices: ["Shays' Rebellion", "Bacon's Rebellion", "The Whiskey Rebellion", "The Stamp Act Protest"], answer: 2, hint: "George Washington led troops to stop it.", dok: 1 },
            { question: "What did George Washington warn against in his Farewell Address?", choices: ["A strong national military", "Political parties and foreign alliances", "Westward expansion", "The creation of public schools"], answer: 1, hint: "He feared these would divide and endanger the young nation.", dok: 1 },
            { question: "The Alien and Sedition Acts, passed under John Adams, heavily restricted what freedom?", choices: ["Freedom of religion", "The right to bear arms", "Freedom of speech and the press", "The right to a speedy trial"], answer: 2, hint: "They made it illegal to criticize the government.", dok: 1 },
            { question: "Who was the primary leader of the Democratic-Republican party?", choices: ["Alexander Hamilton", "John Adams", "George Washington", "Thomas Jefferson"], answer: 3, hint: "He believed in a weaker federal government and an agrarian society.", dok: 1 },
            { question: "What diplomatic incident during John Adams' presidency involved French agents demanding a bribe?", choices: ["The XYZ Affair", "The Corrupt Bargain", "The Citizen Genêt Affair", "The Trent Affair"], answer: 0, hint: "The agents were unnamed in the official reports.", dok: 1 },
            { question: "Which documents argued that states had the right to nullify unconstitutional federal laws?", choices: ["The Federalist Papers", "The Kentucky and Virginia Resolutions", "The Articles of Confederation", "The Bill of Rights"], answer: 1, hint: "They were written secretly by Jefferson and Madison in response to the Alien and Sedition Acts.", dok: 1 },
            { question: "Which Supreme Court case established the principle of judicial review?", choices: ["McCulloch v. Maryland", "Gibbons v. Ogden", "Marbury v. Madison", "Worcester v. Georgia"], answer: 2, hint: "It involved 'midnight judges' appointed by John Adams.", dok: 1 },
            { question: "The peaceful transfer of power between rival political parties for the first time occurred after which election?", choices: ["Election of 1788", "Election of 1796", "Election of 1800", "Election of 1824"], answer: 2, hint: "Thomas Jefferson called it a 'Revolution'.", dok: 1 }
        ],
        unit2: [
            { question: "What 1803 land deal with France doubled the size of the United States?", choices: ["The Gadsden Purchase", "The Florida Purchase", "The Louisiana Purchase", "The Oregon Treaty"], answer: 2, hint: "It was purchased by Thomas Jefferson.", dok: 1 },
            { question: "Who did Thomas Jefferson send to explore the new western territory?", choices: ["Pike and Long", "Marquette and Joliet", "Lewis and Clark", "Boone and Crockett"], answer: 2, hint: "Their group was called the Corps of Discovery.", dok: 1 },
            { question: "What was the British practice of forcing American sailors to serve in their navy called?", choices: ["Blockading", "Impressment", "Embargo", "Conscription"], answer: 1, hint: "This was a major cause of the War of 1812.", dok: 1 },
            { question: "Who wrote 'The Star-Spangled Banner' after witnessing the attack on Fort McHenry?", choices: ["Francis Scott Key", "Thomas Jefferson", "Andrew Jackson", "James Madison"], answer: 0, hint: "He saw that the flag was still there in the morning.", dok: 1 },
            { question: "What battle made Andrew Jackson a national hero, even though the peace treaty was already signed?", choices: ["Battle of Lake Erie", "Battle of Tippecanoe", "Battle of New Orleans", "Battle of Yorktown"], answer: 2, hint: "He defended the mouth of the Mississippi River.", dok: 1 },
            { question: "What foreign policy statement warned Europe not to colonize the Americas?", choices: ["The Truman Doctrine", "The Monroe Doctrine", "Manifest Destiny", "The American System"], answer: 1, hint: "It was issued in 1823 by the 5th president.", dok: 1 },
            { question: "Which Shoshone woman served as a vital guide and interpreter for the Corps of Discovery?", choices: ["Pocahontas", "Sacagawea", "Tecumseh", "Squanto"], answer: 1, hint: "She traveled with them all the way to the Pacific Ocean.", dok: 1 },
            { question: "Which disastrous 1807 law banned all American trade with foreign nations?", choices: ["The Non-Intercourse Act", "The Navigation Acts", "The Embargo Act", "The Tariff of Abominations"], answer: 2, hint: "Jefferson hoped to punish Britain and France, but it ruined the U.S. economy instead.", dok: 1 },
            { question: "Which Native American leader attempted to unite western tribes to fight against American expansion before the War of 1812?", choices: ["Pontiac", "Sitting Bull", "Tecumseh", "Geronimo"], answer: 2, hint: "He was allied with the British and killed at the Battle of the Thames.", dok: 1 },
            { question: "What treaty ended the War of 1812, restoring pre-war borders?", choices: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of San Ildefonso"], answer: 2, hint: "It was signed in Belgium.", dok: 1 }
        ],
        unit3: [
            { question: "The belief that the U.S. was meant to expand to the Pacific Ocean was known as...", choices: ["Imperialism", "Nationalism", "Manifest Destiny", "Sectionalism"], answer: 2, hint: "It translates to 'obvious fate'.", dok: 1 },
            { question: "What invention by Eli Whitney vastly increased the demand for enslaved labor in the South?", choices: ["The Steam Engine", "The Telegraph", "The Cotton Gin", "The Mechanical Reaper"], answer: 2, hint: "It quickly separated seeds from the fiber.", dok: 1 },
            { question: "The forced march of the Cherokee people to Indian Territory is tragically known as the...", choices: ["Trail of Tears", "Long Walk", "Great Migration", "Western Journey"], answer: 0, hint: "Thousands died due to exposure and disease.", dok: 1 },
            { question: "The rapid shift to machine-made goods in factories is known as the...", choices: ["Agricultural Revolution", "Industrial Revolution", "Information Age", "Progressive Era"], answer: 1, hint: "It began in New England with textile mills.", dok: 1 },
            { question: "What man-made waterway connected the Great Lakes to the Atlantic Ocean, revolutionizing trade?", choices: ["The Panama Canal", "The Suez Canal", "The Erie Canal", "The Ohio and Erie Canal"], answer: 2, hint: "It was built in New York state.", dok: 1 },
            { question: "Andrew Jackson rewarded his political supporters with government jobs in a practice called the...", choices: ["Merit System", "Spoils System", "Cabinet System", "Corrupt Bargain"], answer: 1, hint: "To the victor go the spoils.", dok: 1 },
            { question: "Which state threatened to secede during the Nullification Crisis over high federal tariffs?", choices: ["Massachusetts", "Virginia", "South Carolina", "Georgia"], answer: 2, hint: "John C. Calhoun led this protest against the 'Tariff of Abominations'.", dok: 1 },
            { question: "Which technological advancement revolutionized communication during the 1800s?", choices: ["The Telephone", "The Telegraph", "The Radio", "The Printing Press"], answer: 1, hint: "It used Morse Code to send messages over wires.", dok: 1 },
            { question: "What institution did Andrew Jackson famously veto and destroy, believing it only benefited the wealthy?", choices: ["The Supreme Court", "The Department of the Treasury", "The Second Bank of the United States", "The Electoral College"], answer: 2, hint: "He waged a 'Bank War' against Nicholas Biddle.", dok: 1 },
            { question: "Which Supreme Court case ruled that the state of Georgia had no authority over Cherokee territory?", choices: ["Marbury v. Madison", "McCulloch v. Maryland", "Gibbons v. Ogden", "Worcester v. Georgia"], answer: 3, hint: "Andrew Jackson famously ignored this ruling.", dok: 1 }
        ],
        unit4: [
            { question: "What was the first public meeting focused on women's rights in the U.S.?", choices: ["The Albany Congress", "The Boston Tea Party", "The Seneca Falls Convention", "The Constitutional Convention"], answer: 2, hint: "It was held in New York in 1848.", dok: 1 },
            { question: "Who was the famous 'conductor' on the Underground Railroad who never lost a passenger?", choices: ["Sojourner Truth", "Harriet Tubman", "Dorothea Dix", "Elizabeth Cady Stanton"], answer: 1, hint: "She was known as 'Moses' to her people.", dok: 1 },
            { question: "Which reformer campaigned to improve conditions in prisons and mental asylums?", choices: ["Horace Mann", "William Lloyd Garrison", "Dorothea Dix", "Frederick Douglass"], answer: 2, hint: "She convinced legislatures to build humane hospitals.", dok: 1 },
            { question: "What book by Harriet Beecher Stowe exposed the cruelty of slavery to Northern readers?", choices: ["Common Sense", "The Liberator", "Uncle Tom's Cabin", "The North Star"], answer: 2, hint: "Lincoln supposedly said it started the great war.", dok: 1 },
            { question: "Which religious movement swept the nation in the early 1800s, inspiring many social reform movements?", choices: ["The Enlightenment", "The First Great Awakening", "The Second Great Awakening", "The Protestant Reformation"], answer: 2, hint: "It emphasized free will and improving society.", dok: 1 },
            { question: "Who was a formerly enslaved man who became a powerful speaker and published the abolitionist newspaper 'The North Star'?", choices: ["William Lloyd Garrison", "Frederick Douglass", "Nat Turner", "John Brown"], answer: 1, hint: "He taught himself how to read and write.", dok: 1 },
            { question: "Which movement sought to ban the consumption and sale of alcohol?", choices: ["The Suffrage Movement", "The Abolition Movement", "The Temperance Movement", "The Transcendentalist Movement"], answer: 2, hint: "They blamed alcohol for poverty and family violence.", dok: 1 },
            { question: "Who wrote the 'Declaration of Sentiments' demanding equality for women?", choices: ["Harriet Tubman", "Susan B. Anthony", "Elizabeth Cady Stanton", "Dorothea Dix"], answer: 2, hint: "She organized the Seneca Falls Convention.", dok: 1 },
            { question: "Which reformer is known as the 'Father of American Public Schools'?", choices: ["Horace Mann", "William Lloyd Garrison", "Lyman Beecher", "Thomas Gallaudet"], answer: 0, hint: "He believed education was the great equalizer.", dok: 1 },
            { question: "What was the name of the radical abolitionist newspaper published by William Lloyd Garrison?", choices: ["The North Star", "The Liberator", "The Emancipator", "The Freedom Press"], answer: 1, hint: "He demanded immediate emancipation without compensation.", dok: 1 }
        ],
        unit5: [
            { question: "Which Supreme Court case ruled that enslaved people were property and could not sue in court?", choices: ["Marbury v. Madison", "Worcester v. Georgia", "Dred Scott v. Sandford", "Plessy v. Ferguson"], answer: 2, hint: "It declared the Missouri Compromise unconstitutional.", dok: 1 },
            { question: "What law allowed slave catchers to travel into Northern states to capture escaped enslaved people?", choices: ["The Missouri Compromise", "The Fugitive Slave Act", "The Kansas-Nebraska Act", "The Homestead Act"], answer: 1, hint: "It was part of the Compromise of 1850.", dok: 1 },
            { question: "The violence that erupted over the issue of popular sovereignty in western territories was known as...", choices: ["Bleeding Kansas", "Shays' Rebellion", "The Whiskey Rebellion", "Harper's Ferry"], answer: 0, hint: "Pro-slavery and anti-slavery settlers fought each other.", dok: 1 },
            { question: "Where were the first shots of the American Civil War fired?", choices: ["Gettysburg", "Antietam", "Fort Sumter", "Appomattox"], answer: 2, hint: "It was a federal fort located in South Carolina.", dok: 1 },
            { question: "Who was elected President of the United States in 1860, triggering the secession of Southern states?", choices: ["James Buchanan", "Jefferson Davis", "Stephen Douglas", "Abraham Lincoln"], answer: 3, hint: "He ran as a Republican.", dok: 1 },
            { question: "Who served as the President of the Confederate States of America?", choices: ["Robert E. Lee", "Stonewall Jackson", "Jefferson Davis", "John C. Calhoun"], answer: 2, hint: "He was a former Senator from Mississippi.", dok: 1 },
            { question: "Which document freed enslaved people specifically in the Confederate states currently in rebellion?", choices: ["The 13th Amendment", "The Declaration of Independence", "The Emancipation Proclamation", "The Gettysburg Address"], answer: 2, hint: "Issued by Lincoln after the Battle of Antietam.", dok: 1 },
            { question: "Which three-day battle in Pennsylvania is considered the turning point of the Civil War?", choices: ["Battle of Bull Run", "Battle of Antietam", "Battle of Gettysburg", "Battle of Vicksburg"], answer: 2, hint: "It was the bloodiest battle of the war.", dok: 1 },
            { question: "Where did General Robert E. Lee surrender to General Ulysses S. Grant, effectively ending the Civil War?", choices: ["Richmond", "Appomattox Court House", "Gettysburg", "Washington D.C."], answer: 1, hint: "It took place in a small Virginia town.", dok: 1 },
            { question: "What was the strategic goal of the Union capturing Vicksburg and New Orleans?", choices: ["To capture the Confederate capital.", "To gain control of the Mississippi River and split the Confederacy in two.", "To force France into the war.", "To secure the borders of Mexico."], answer: 1, hint: "It was a key part of the Anaconda Plan.", dok: 1 }
        ]
    },
    HARD: {
        unit1: [
            { question: "Analyze how the differing philosophies of Alexander Hamilton and Thomas Jefferson laid the groundwork for the first political parties.", choices: ["Their agreement on foreign policy united the nation.", "They disagreed on the economy and federal power.", "Both leaders advocated for a weak central government, uniting voters.", "Their personal rivalry was the sole cause of the divisions."], answer: 1, hint: "Consider their contrasting visions of an industrial vs. agrarian society.", dok: 4 },
            { question: "Evaluate the significance of George Washington's response to the Whiskey Rebellion.", choices: ["It exposed the crippling weakness of the federal government.", "It proved the government could enforce its laws.", "It led to the immediate and permanent repeal of the federal tax.", "It caused several states to threaten secession from the Union."], answer: 1, hint: "Compare this decisive action to the government's inability to handle Shays' Rebellion.", dok: 4 },
            { question: "Explain how the Federalist defense of the National Bank relied on a 'loose construction' interpretation of the Constitution.", choices: ["They argued the Constitution explicitly mentioned a bank.", "They used the 'Necessary and Proper' clause.", "They claimed the bank was unconstitutional but necessary anyway.", "They argued state banks should hold supreme authority."], answer: 1, hint: "They believed the government had implied powers not explicitly written in the text.", dok: 4 },
            { question: "Analyze the political consequences of the Alien and Sedition Acts passed under John Adams.", choices: ["They successfully unified the country against the threat of France.", "They were attacked as unconstitutional.", "They were immediately struck down by the Supreme Court.", "They had no real political impact and were widely ignored."], answer: 1, hint: "How would a law that criminalizes government criticism affect a democracy?", dok: 3 },
            { question: "Evaluate the long-term historical impact of the Election of 1800 (the 'Revolution of 1800').", choices: ["It proved that power could not be transferred peacefully between opposing parties.", "It resulted in the dissolution of the Electoral College.", "It established the peaceful transfer of power.", "It led to a constitutional crisis that permanently weakened the presidency."], answer: 2, hint: "What did it mean for the stability of the Republic that the ruling party stepped down after losing?", dok: 4 },
            { question: "Analyze the constitutional significance of the Supreme Court's decision in Marbury v. Madison.", choices: ["It gave the President the power to veto court rulings.", "It established judicial review.", "It stripped the federal courts of all authority over state laws.", "It forced the creation of the Bill of Rights."], answer: 1, hint: "Chief Justice John Marshall greatly expanded the power of the Judicial branch.", dok: 4 },
            { question: "Evaluate the arguments presented in the Kentucky and Virginia Resolutions.", choices: ["They argued that the federal government had absolute power over the states.", "They argued states could nullify unconstitutional federal laws.", "They demanded an immediate declaration of war against France.", "They called for the total abolition of slavery."], answer: 1, hint: "Jefferson and Madison wrote them to fight the Alien and Sedition Acts.", dok: 4 },
            { question: "Explain why George Washington warned against 'permanent alliances' in his Farewell Address.", choices: ["He wanted the US to conquer Europe.", "He believed alliances would drag the nation into European wars.", "He believed the US should only ally with Great Britain.", "He wanted to isolate the US from all global trade."], answer: 1, hint: "The US was weak and needed time to build its own strength.", dok: 3 },
            { question: "Analyze the economic divide between the Federalists and Democratic-Republicans.", choices: ["Federalists wanted an agricultural economy; Republicans wanted an industrial one.", "Federalists favored industry and a Bank; Republicans favored agriculture.", "Both parties agreed on a strictly agricultural economy.", "Neither party cared about economic issues."], answer: 1, hint: "Think of Hamilton's background in New York vs. Jefferson's background in Virginia.", dok: 3 },
            { question: "Evaluate the impact of the XYZ Affair on American foreign policy.", choices: ["It led to a strong, permanent alliance with France.", "It caused public outrage and an undeclared 'Quasi-War'.", "It resulted in the immediate purchase of the Louisiana Territory.", "It forced the US to surrender its navy to Britain."], answer: 1, hint: "'Millions for defense, but not one cent for tribute!'", dok: 3 }
        ],
        unit2: [
            { question: "Analyze the constitutional dilemma Thomas Jefferson faced regarding the Louisiana Purchase.", choices: ["He believed the purchase was explicitly authorized by the Constitution.", "He sought to pass a constitutional amendment before finalizing the treaty.", "He used 'loose construction' to justify the buy.", "He ignored the Constitution entirely and bypassed Congress."], answer: 2, hint: "As a strict constructionist, he struggled because the Constitution didn't explicitly grant the power to buy land.", dok: 4 },
            { question: "Evaluate the most significant long-term domestic consequence of the War of 1812 for the United States.", choices: ["The U.S. successfully annexed large portions of Canada.", "The war triggered a severe, decades-long economic depression.", "The war destroyed American manufacturing capabilities in New England.", "It boosted nationalism and domestic industry."], answer: 3, hint: "Cut off from British goods, Americans had to start making things themselves while feeling a new sense of pride.", dok: 4 },
            { question: "Compare the motivations of Native American groups who allied with Britain during the War of 1812 with those who allied with the U.S.", choices: ["All Native American groups universally allied with Britain.", "They allied to protect their land and sovereignty.", "All Native American groups remained strictly neutral.", "Motivations were based entirely on the fur trade."], answer: 1, hint: "Think about who represented the most immediate threat to indigenous lands at the time.", dok: 3 },
            { question: "Explain the psychological and political impact of the Battle of New Orleans.", choices: ["It was viewed as a minor skirmish with no real significance.", "It boosted national pride and made Jackson a hero.", "Jackson's defeat at the battle ruined his political career.", "It was seen as an embarrassing and unnecessary loss of life."], answer: 1, hint: "Focus on the symbolic importance of overwhelmingly defeating the British military.", dok: 3 },
            { question: "Synthesize how the Monroe Doctrine shifted American foreign policy.", choices: ["It declared the U.S. would actively intervene in all European wars.", "It warned Europe against further colonization in the Americas.", "It surrendered control of South America to Spain.", "It proposed a global peacekeeping organization."], answer: 1, hint: "The U.S. was asserting itself as the dominant power in the Americas.", dok: 4 },
            { question: "Analyze the economic impact of Jefferson's Embargo Act of 1807.", choices: ["It successfully starved Britain and France into respecting American neutrality.", "It devastated the American economy.", "It caused an immediate boom in American agricultural exports.", "It had no noticeable effect on the U.S. economy."], answer: 1, hint: "By stopping all foreign trade, the US hurt itself the most.", dok: 4 },
            { question: "Evaluate the long-term scientific and geographic significance of the Lewis and Clark expedition.", choices: ["They found the Northwest Passage, revolutionizing global trade.", "They failed to reach the Pacific Ocean.", "They mapped the West and strengthened U.S. claims.", "They accidentally triggered a war with Spain over Texas."], answer: 2, hint: "Their journals provided massive amounts of data about the West.", dok: 3 },
            { question: "Explain how the British policy of impressment violated American sovereignty.", choices: ["Britain was forcing American citizens to pay British taxes.", "Britain was seizing American ships and kidnapping sailors.", "Britain was building military forts inside the United States.", "Britain was refusing to buy American cotton."], answer: 1, hint: "It was essentially the kidnapping of sailors.", dok: 3 },
            { question: "Analyze the role of the 'War Hawks' in Congress leading up to the War of 1812.", choices: ["They desperately wanted to maintain peace and trade with Britain.", "They were primarily Northern merchants who feared a war would ruin the economy.", "They pushed for war to defend honor and expand territory.", "They wanted to form a military alliance with Native Americans."], answer: 2, hint: "Figures like Henry Clay and John C. Calhoun wanted to prove America's strength.", dok: 3 },
            { question: "Evaluate the significance of the Treaty of Ghent.", choices: ["It resulted in massive territorial gains for the United States.", "It forced the U.S. to pay reparations to Great Britain.", "It restored pre-war borders and established American power.", "It outlawed slavery in the western territories."], answer: 2, hint: "The treaty essentially hit the 'reset button' to how things were before the war.", dok: 4 }
        ],
        unit3: [
            { question: "Analyze how the invention of the cotton gin contributed to the growth of sectionalism.", choices: ["It reduced the need for enslaved labor, bringing the North and South together politically.", "It made the Southern economy more industrial, mirroring the North.", "It entrenched slavery in the South.", "It had no significant impact on the relationship between the two regions."], answer: 2, hint: "How did one invention reinforce two totally different economic systems?", dok: 4 },
            { question: "Evaluate President Andrew Jackson's response to the Supreme Court ruling in Worcester v. Georgia.", choices: ["He utilized the military to enforce the ruling and protect Cherokee lands.", "He defied the Court and allowed forced removal.", "He asked Congress to rewrite the Indian Removal Act.", "He resigned from office in protest of the decision."], answer: 1, hint: "He essentially said, 'John Marshall has made his decision; now let him enforce it.'", dok: 4 },
            { question: "Explain how the ideology of Manifest Destiny influenced U.S. actions regarding territorial expansion.", choices: ["It encouraged diplomacy to preserve peace at all costs.", "It justified aggressive expansion and war.", "It focused national attention solely on acquiring the Oregon Territory.", "It was used by opponents of expansion to argue against seizing new lands."], answer: 1, hint: "If a nation believes it is 'destined' by God to control the continent, how does it view obstacles?", dok: 3 },
            { question: "Analyze the economic impact of the Erie Canal and the Transportation Revolution.", choices: ["It made transportation slower and significantly more expensive.", "It connected markets and lowered shipping costs.", "It primarily benefited only the state of New York.", "It caused a total collapse of the Southern economy."], answer: 1, hint: "Think about how moving goods efficiently by water changed the national economy.", dok: 3 },
            { question: "Synthesize the constitutional arguments at the center of the Nullification Crisis.", choices: ["It was a debate over whether the President could declare war.", "It tested states' rights to reject federal laws.", "It argued that the Supreme Court was an illegal institution.", "It focused entirely on whether the National Bank should be re-chartered."], answer: 1, hint: "South Carolina threatened to secede if the federal government forced them to pay.", dok: 4 },
            { question: "Evaluate the consequences of Andrew Jackson's 'Bank War'.", choices: ["It created a long era of stable economic growth.", "It triggered the Panic of 1837 and economic depression.", "It successfully distributed wealth equally to all American citizens.", "It forced the United States to abandon capitalism."], answer: 1, hint: "Removing the central bank caused massive financial instability.", dok: 4 },
            { question: "Analyze how the Market Revolution changed daily life for Americans.", choices: ["People stopped buying goods and only bartered.", "It shifted society to a national economy of buying and selling.", "It forced everyone to move out of cities and back to farms.", "It outlawed the use of currency."], answer: 1, hint: "Think about the transition from homespun clothes to factory-made textiles.", dok: 3 },
            { question: "Explain the political shift represented by 'Jacksonian Democracy'.", choices: ["It restricted voting rights only to the wealthiest landowners.", "It expanded voting rights for all white men.", "It abolished the presidency and gave all power to Congress.", "It granted women the right to vote nationwide."], answer: 1, hint: "Jackson appealed to the 'common man'.", dok: 3 },
            { question: "Compare the economies of the North and South prior to the Civil War.", choices: ["Both were entirely reliant on heavy industry.", "North was industrial; South was agrarian and dependent on slavery.", "The South was highly industrial; the North was purely agricultural.", "Both regions abandoned agriculture in favor of shipping."], answer: 1, hint: "Textile mills vs. Cotton plantations.", dok: 4 },
            { question: "Synthesize the 'push' and 'pull' factors driving immigration in the 1840s.", choices: ["Immigrants were pushed by religious freedom and pulled by famine.", "Famine and unrest pushed them; jobs pulled them.", "The only factor was the California Gold Rush.", "The U.S. government forced them to immigrate."], answer: 1, hint: "Connect disasters in Europe with opportunities in a growing America.", dok: 4 }
        ],
        unit4: [
            { question: "Analyze the significance of the language used in the 'Declaration of Sentiments' at the Seneca Falls Convention.", choices: ["It was written in French to appeal to international allies.", "It mimicked the Declaration of Independence.", "It focused entirely on the abolition of slavery rather than women's rights.", "It was a legal contract to establish public schools."], answer: 1, hint: "Think about the phrase: 'We hold these truths to be self-evident: that all men and women are created equal.'", dok: 4 },
            { question: "Evaluate the impact of Harriet Beecher Stowe's 'Uncle Tom's Cabin'.", choices: ["It convinced the South to peacefully abolish slavery.", "It outraged the North and fueled the abolitionist cause.", "It was widely ignored and had no impact on public opinion.", "It successfully ended the Fugitive Slave Act."], answer: 1, hint: "It brought the emotional horrors of slavery into Northern living rooms.", dok: 4 },
            { question: "Compare the approaches of abolitionists William Lloyd Garrison and Frederick Douglass.", choices: ["Both believed the Constitution was inherently pro-slavery.", "Garrison condemned the Constitution; Douglass used it.", "Douglass advocated for violence, while Garrison strictly advocated for gradual political reform.", "Both focused exclusively on colonizing freed slaves in Africa."], answer: 1, hint: "One burned the document; the other cited its ideals.", dok: 4 },
            { question: "Explain how the Second Great Awakening fueled the era's social reform movements.", choices: ["It taught that society was perfect and needed no changing.", "It emphasized moral duty to improve society.", "It focused entirely on building new churches and ignored social issues.", "It argued that only the government could fix social problems."], answer: 1, hint: "If you can save your own soul, you can save society.", dok: 3 },
            { question: "Analyze the connection between the abolitionist movement and the women's rights movement.", choices: ["They were bitter enemies who constantly fought.", "Women fighting for abolition realized they lacked rights too.", "The women's rights movement actively opposed the abolition of slavery.", "There was no connection between the two movements."], answer: 1, hint: "Figures like Elizabeth Cady Stanton started as abolitionists.", dok: 4 },
            { question: "Evaluate the success of Dorothea Dix's reform efforts.", choices: ["She failed to pass any significant legislation.", "She convinced states to build humane asylums.", "She focused only on passing the 18th Amendment.", "She successfully banned all prisons in the United States."], answer: 1, hint: "She presented horrific facts to lawmakers to force change.", dok: 3 },
            { question: "Explain the philosophy behind Horace Mann's push for public education reform.", choices: ["He believed only wealthy children deserved to learn to read.", "He argued free education was essential for democracy.", "He wanted all schools to be controlled by religious organizations.", "He believed education should only focus on farming techniques."], answer: 1, hint: "Education is the 'great equalizer'.", dok: 3 },
            { question: "Analyze the role of the Underground Railroad in resisting the institution of slavery.", choices: ["It was a legal organization sanctioned by the Supreme Court.", "It was an illegal network helping slaves escape.", "It was a literal train that ran from Atlanta to New York.", "It was primarily a fundraising organization to buy the freedom of enslaved people."], answer: 1, hint: "It relied on secrecy and the bravery of 'conductors'.", dok: 3 },
            { question: "Synthesize the goals of the Temperance Movement.", choices: ["To expand the right to vote to all citizens.", "To combat societal damage caused by alcohol.", "To improve the working conditions in textile factories.", "To encourage the consumption of alcohol for medical purposes."], answer: 1, hint: "Reformers believed alcohol was the root of society's evils.", dok: 3 },
            { question: "Evaluate the challenges faced by the early Women's Rights movement.", choices: ["They were immediately successful in gaining the right to vote.", "They faced intense societal backlash and legal barriers.", "They lacked strong leadership or clear goals.", "They were fully supported by the majority of male politicians."], answer: 1, hint: "Society viewed their demands as radical and unnatural.", dok: 4 }
        ],
        unit5: [
            { question: "Evaluate the impact of the Fugitive Slave Act of 1850 on Northern society.", choices: ["It made Northerners more sympathetic to Southern slaveholders.", "It outraged Northerners and increased anti-slavery views.", "It completely stopped all escapes via the Underground Railroad.", "It peacefully resolved the tensions between the North and South."], answer: 1, hint: "It brought the brutal reality of slavery directly into free states.", dok: 4 },
            { question: "Explain how the concept of 'popular sovereignty' in the Kansas-Nebraska Act led to 'Bleeding Kansas.'", choices: ["It successfully banned slavery in the territory.", "Voting on slavery triggered violent clashes.", "It forced all Native Americans to leave the territory.", "It resulted in a unanimous, peaceful vote."], answer: 1, hint: "When the people decide the law, extremes on both sides will try to rig the outcome.", dok: 3 },
            { question: "Analyze the core legal reasoning behind the Supreme Court's Dred Scott decision.", choices: ["The Court ruled Scott was free because he lived in a free state.", "It ruled that Black Americans were not citizens.", "The Court ruled that slavery was illegal nationwide.", "The Court refused to hear the case entirely."], answer: 1, hint: "Chief Justice Taney's decision essentially declared the Missouri Compromise unconstitutional.", dok: 4 },
            { question: "Analyze how the Election of 1860 demonstrated the severe sectional divide in the United States.", choices: ["Lincoln won unanimously across all states.", "Lincoln won without a single Southern vote.", "The election was delayed due to the ongoing violence in Kansas.", "A Southern Democrat won the election, causing the North to secede."], answer: 1, hint: "The South felt they had lost all political power in the national government.", dok: 4 },
            { question: "Evaluate the strategic purpose of the Emancipation Proclamation.", choices: ["It instantly freed all enslaved people in the United States.", "It made the war about ending slavery.", "It was purely a symbolic gesture with no real impact.", "It surrendered Northern territory to the Confederacy."], answer: 1, hint: "It was a military measure that changed the moral character of the war.", dok: 4 },
            { question: "Explain the significance of the Battle of Gettysburg.", choices: ["It was the first battle of the war.", "It halted Confederate momentum permanently.", "It resulted in the immediate surrender of the Confederacy.", "It was the battle where Stonewall Jackson was killed."], answer: 1, hint: "It is known as the 'High Water Mark of the Confederacy'.", dok: 3 },
            { question: "Analyze the message of Abraham Lincoln's Gettysburg Address.", choices: ["He declared that the South would be harshly punished.", "He framed the war as a test of democracy and equality.", "He announced the immediate end of the war.", "He formally declared the independence of the Confederate States."], answer: 1, hint: "Four score and seven years ago...", dok: 4 },
            { question: "Evaluate the impact of John Brown's raid on Harper's Ferry.", choices: ["It successfully started a massive slave rebellion.", "It convinced the South that Northerners would use violence.", "It resulted in a peaceful compromise between North and South.", "It convinced the North to support the expansion of slavery."], answer: 1, hint: "He became a martyr in the North and a terrorist in the South.", dok: 4 },
            { question: "Synthesize the main components of the Compromise of 1850.", choices: ["It abolished slavery nationwide.", "California became free; harsh Fugitive Slave Law.", "It allowed Texas to expand its borders to the Pacific.", "It established the Missouri Compromise line across the entire continent."], answer: 1, hint: "It tried to balance the demands of both sections after the Mexican-American War.", dok: 4 },
            { question: "Analyze the role of Louisiana's geography during the Civil War.", choices: ["It was entirely ignored by both sides.", "Control of the Mississippi made it a prime target.", "Its mountains provided an impenetrable defense for the Confederacy.", "It served as the primary manufacturing hub for Union weapons."], answer: 1, hint: "Whoever controls the mouth of the river controls the trade of the continent.", dok: 3 }
        ]
    },
    SKIBIDI: {
        unit1: [
            { question: "The first President of the United States was George ___.", answer: ["washington"], hint: "He set the precedent of a two-term limit.", dok: 1 },
            { question: "The leader of the Federalist Party and first Secretary of the Treasury was Alexander ___.", answer: ["hamilton"], hint: "He pushed for a National Bank.", dok: 1 },
            { question: "The 1794 uprising of farmers protesting a federal tax was the ___ Rebellion.", answer: ["whiskey", "whiskeys"], hint: "Washington led troops to stop it.", dok: 1 },
            { question: "The controversial laws passed by John Adams that limited free speech were the Alien and ___ Acts.", answer: ["sedition"], hint: "They targeted immigrants and government critics.", dok: 1 },
            { question: "The diplomatic incident where French agents demanded a bribe from the U.S. was the ___ Affair.", answer: ["xyz"], hint: "It involved three unnamed agents.", dok: 1 },
            { question: "The political party founded by Thomas Jefferson was the ___-Republican party.", answer: ["democratic"], hint: "They favored a strict interpretation of the Constitution.", dok: 1 },
            { question: "The Supreme Court case that established Judicial Review was Marbury v. ___.", answer: ["madison"], hint: "It allowed the court to strike down laws.", dok: 1 },
            { question: "The documents secretly written by Jefferson and Madison claiming states could nullify laws were the Kentucky and ___ Resolutions.", answer: ["virginia"], hint: "It argued for states' rights.", dok: 1 },
            { question: "Washington warned against political parties and foreign ___ in his Farewell Address.", answer: ["alliances", "alliance"], hint: "He wanted the US to stay neutral.", dok: 1 },
            { question: "The second President of the United States was John ___.", answer: ["adams"], hint: "He was a Federalist who passed the Alien and Sedition Acts.", dok: 1 }
        ],
        unit2: [
            { question: "The land deal that doubled the size of the United States in 1803 was the ___ Purchase.", answer: ["louisiana"], hint: "Thomas Jefferson bought it from France.", dok: 1 },
            { question: "The explorers sent by Jefferson to map the new western territory were ___ and Clark.", answer: ["lewis"], hint: "They were guided by Sacagawea.", dok: 1 },
            { question: "The British practice of forcing American sailors into their navy is called ___.", answer: ["impressment"], hint: "It was a major cause of the War of 1812.", dok: 1 },
            { question: "The national anthem, 'The Star-Spangled Banner,' was written by Francis Scott ___.", answer: ["key"], hint: "He watched the bombing of Fort McHenry.", dok: 1 },
            { question: "The American general who became a hero at the Battle of New Orleans was Andrew ___.", answer: ["jackson"], hint: "He later became the 7th President.", dok: 1 },
            { question: "The Shoshone woman who guided the Lewis and Clark expedition was ___.", answer: ["sacagawea", "sacajawea"], hint: "She helped them communicate with other tribes.", dok: 1 },
            { question: "The policy warning European nations to stay out of the Americas is the ___ Doctrine.", answer: ["monroe"], hint: "Issued in 1823.", dok: 1 },
            { question: "The disastrous 1807 law that banned all foreign trade was the ___ Act.", answer: ["embargo"], hint: "It ruined the American economy.", dok: 1 },
            { question: "The Native American leader who tried to unite tribes against American expansion was ___.", answer: ["tecumseh"], hint: "He allied with the British in the War of 1812.", dok: 1 },
            { question: "The treaty that ended the War of 1812 was the Treaty of ___.", answer: ["ghent"], hint: "It changed no borders.", dok: 1 }
        ],
        unit3: [
            { question: "The belief that the U.S. was destined to expand to the Pacific Ocean is Manifest ___.", answer: ["destiny"], hint: "It means 'obvious fate'.", dok: 1 },
            { question: "The forced removal of the Cherokee people to Indian Territory is known as the Trail of ___.", answer: ["tears"], hint: "Thousands died on this tragic journey.", dok: 1 },
            { question: "The invention by Eli Whitney that vastly increased the demand for slavery was the ___ gin.", answer: ["cotton"], hint: "It separated seeds from fibers.", dok: 1 },
            { question: "The man-made waterway connecting the Great Lakes to New York City is the ___ Canal.", answer: ["erie"], hint: "It revolutionized shipping.", dok: 1 },
            { question: "The shift from making goods by hand to making them in factories with machines is the ___ Revolution.", answer: ["industrial"], hint: "It began in New England.", dok: 1 },
            { question: "Andrew Jackson's practice of giving government jobs to his supporters is the ___ System.", answer: ["spoils"], hint: "To the victor go the...", dok: 1 },
            { question: "The crisis where South Carolina threatened to secede over a high tariff was the ___ Crisis.", answer: ["nullification"], hint: "They claimed the right to reject federal law.", dok: 1 },
            { question: "The institution that Andrew Jackson vetoed and destroyed was the National ___.", answer: ["bank"], hint: "He claimed it only helped the wealthy.", dok: 1 },
            { question: "The Native American tribe that was forced to march the Trail of Tears was the ___.", answer: ["cherokee"], hint: "They had won their Supreme Court case but were removed anyway.", dok: 1 },
            { question: "The invention that allowed messages to be sent quickly over wires using Morse Code was the ___.", answer: ["telegraph"], hint: "It revolutionized communication.", dok: 1 }
        ],
        unit4: [
            { question: "The first women's rights convention was held in 1848 at ___ Falls, New York.", answer: ["seneca"], hint: "They wrote the Declaration of Sentiments.", dok: 1 },
            { question: "The famous conductor of the Underground Railroad was Harriet ___.", answer: ["tubman"], hint: "She was known as 'Moses'.", dok: 1 },
            { question: "The author of the influential anti-slavery novel 'Uncle Tom's Cabin' was Harriet Beecher ___.", answer: ["stowe"], hint: "Her book angered the South.", dok: 1 },
            { question: "The reformer who worked to improve prisons and mental asylums was Dorothea ___.", answer: ["dix"], hint: "She investigated terrible conditions in jails.", dok: 1 },
            { question: "The formerly enslaved man who published the abolitionist paper 'The North Star' was Frederick ___.", answer: ["douglass"], hint: "He was a powerful public speaker.", dok: 1 },
            { question: "The radical abolitionist who published 'The Liberator' was William Lloyd ___.", answer: ["garrison"], hint: "He demanded immediate emancipation.", dok: 1 },
            { question: "The movement that sought to ban the sale and drinking of alcohol was the ___ Movement.", answer: ["temperance"], hint: "They blamed it for societal problems.", dok: 1 },
            { question: "The reformer known as the 'Father of American Public Schools' was Horace ___.", answer: ["mann"], hint: "He believed education was the great equalizer.", dok: 1 },
            { question: "The religious revival movement that inspired people to fix social problems was the Second Great ___.", answer: ["awakening"], hint: "It stressed free will.", dok: 1 },
            { question: "The primary organizer of the Seneca Falls Convention was Elizabeth Cady ___.", answer: ["stanton"], hint: "She wrote the Declaration of Sentiments.", dok: 1 }
        ],
        unit5: [
            { question: "The Supreme Court case that ruled enslaved people were property, not citizens, was the ___ Scott decision.", answer: ["dred"], hint: "He sued for his freedom after living in free territory.", dok: 1 },
            { question: "The law that forced Northerners to help return escaped slaves was the ___ Slave Act.", answer: ["fugitive"], hint: "It outraged abolitionists.", dok: 1 },
            { question: "The violence that erupted over voting on slavery in the territories was known as Bleeding ___.", answer: ["kansas"], hint: "Pro and anti-slavery settlers fought each other.", dok: 1 },
            { question: "The first shots of the Civil War were fired at Fort ___.", answer: ["sumter"], hint: "Located in South Carolina.", dok: 1 },
            { question: "The President of the United States during the Civil War was Abraham ___.", answer: ["lincoln"], hint: "His election in 1860 triggered secession.", dok: 1 },
            { question: "The President of the Confederate States of America was Jefferson ___.", answer: ["davis"], hint: "He was from Mississippi.", dok: 1 },
            { question: "The document that freed slaves in the rebelling states was the ___ Proclamation.", answer: ["emancipation"], hint: "Issued after the Battle of Antietam.", dok: 1 },
            { question: "The bloody 3-day battle that was the turning point of the war was the Battle of ___.", answer: ["gettysburg"], hint: "Fought in Pennsylvania.", dok: 1 },
            { question: "Robert E. Lee surrendered to Ulysses S. Grant at ___ Court House.", answer: ["appomattox"], hint: "This ended the war.", dok: 1 },
            { question: "The act of a state leaving the Union is called ___.", answer: ["secession", "seceding"], hint: "South Carolina was the first to do this.", dok: 1 }
        ]
    },
    MYTH: {
        unit1: [
            { question: "MYTH or FACT: George Washington chopped down his father's cherry tree and confessed to it.", isFact: false, explanation: "MYTH: This famous story was completely invented by an early biographer, Parson Weems, to illustrate Washington's honesty. There is no historical evidence it happened." },
            { question: "MYTH or FACT: The Whiskey Rebellion proved the new federal government was weak and powerless.", isFact: false, explanation: "MYTH: It proved the exact opposite. By raising an army to crush the rebellion, Washington proved the new Constitutional government could enforce its laws, unlike the Articles of Confederation." },
            { question: "MYTH or FACT: Alexander Hamilton and Thomas Jefferson's disagreements led to the creation of the first political parties.", isFact: true, explanation: "FACT: Their intense conflicts over the National Bank, the economy, and federal power directly resulted in the formation of the Federalist and Democratic-Republican parties." },
            { question: "MYTH or FACT: The Alien and Sedition Acts were created to expand free speech rights.", isFact: false, explanation: "MYTH: They severely restricted free speech, allowing the government to jail newspaper editors and politicians who criticized President John Adams and the Federalist party." },
            { question: "MYTH or FACT: The Supreme Court case Marbury v. Madison established the power of judicial review.", isFact: true, explanation: "FACT: This landmark case established the Supreme Court's authority to declare laws or executive actions unconstitutional, cementing its role as a co-equal branch of government." },
            { question: "MYTH or FACT: George Washington was a member of the Federalist Party.", isFact: false, explanation: "MYTH: Washington officially remained non-partisan and warned against political parties, though his policies generally aligned with Hamilton and the Federalists." },
            { question: "MYTH or FACT: The XYZ Affair resulted in a massive, declared war between the United States and France.", isFact: false, explanation: "MYTH: It led to an undeclared naval conflict known as the 'Quasi-War', but John Adams successfully kept the nation out of a full-scale war." },
            { question: "MYTH or FACT: The Kentucky and Virginia Resolutions argued that states had the right to ignore federal laws.", isFact: true, explanation: "FACT: Written secretly by Jefferson and Madison, they introduced the controversial theory of 'nullification' to fight the Alien and Sedition Acts." },
            { question: "MYTH or FACT: Thomas Jefferson firmly believed in a strong, central, industrial government.", isFact: false, explanation: "MYTH: Jefferson believed in a weaker federal government, strong states' rights, and an economy based on agriculture (the yeoman farmer)." },
            { question: "MYTH or FACT: John Adams refused to leave the presidency when he lost the Election of 1800.", isFact: false, explanation: "MYTH: Despite a bitter election, Adams stepped down peacefully, establishing the crucial precedent of a peaceful transfer of power between rival parties." }
        ],
        unit2: [
            { question: "MYTH or FACT: Thomas Jefferson fought a war with France to conquer the Louisiana Territory.", isFact: false, explanation: "MYTH: He purchased it peacefully. Napoleon Bonaparte, needing funds for his wars in Europe, sold the massive territory to the U.S. for $15 million in 1803." },
            { question: "MYTH or FACT: The Lewis and Clark expedition discovered a direct, all-water route to the Pacific Ocean.", isFact: false, explanation: "MYTH: While they successfully mapped the region and reached the ocean, they proved that a 'Northwest Passage' (a continuous water route) did not exist across the continent." },
            { question: "MYTH or FACT: The United States decisively won the War of 1812 and took over Canada.", isFact: false, explanation: "MYTH: The war was largely a military stalemate. The Treaty of Ghent restored all pre-war borders, though the U.S. did gain a surge of national pride and international respect." },
            { question: "MYTH or FACT: The Battle of New Orleans was fought after the peace treaty ending the war had already been signed.", isFact: true, explanation: "FACT: The Treaty of Ghent was signed in Europe weeks before the battle, but news traveled slowly across the Atlantic by ship, so the armies in Louisiana didn't know the war was over." },
            { question: "MYTH or FACT: The 'Era of Good Feelings' was a period of intense political fighting and civil war.", isFact: false, explanation: "MYTH: It was a period following the War of 1812 characterized by strong national unity and the temporary collapse of the two-party system, leaving only the Democratic-Republicans." },
            { question: "MYTH or FACT: The Monroe Doctrine warned European nations against interfering in the Western Hemisphere.", isFact: true, explanation: "FACT: Issued in 1823, it declared that the Americas were off-limits to further European colonization and that the U.S. would view any interference as a hostile act." },
            { question: "MYTH or FACT: Sacagawea was the primary leader who commanded the Lewis and Clark expedition.", isFact: false, explanation: "MYTH: While she was a vital guide, translator, and symbol of peace for the Corps of Discovery, Meriwether Lewis and William Clark were the commissioned commanders." },
            { question: "MYTH or FACT: The Embargo Act of 1807 successfully forced Britain and France to respect American neutrality.", isFact: false, explanation: "MYTH: The embargo was a spectacular failure that devastated the American economy—especially New England shipping—while barely affecting the European powers." },
            { question: "MYTH or FACT: Impressment meant the British were forcing American sailors to pay taxes on their cargo.", isFact: false, explanation: "MYTH: Impressment was the practice of stopping American ships, claiming the sailors were British deserters, and kidnapping them to serve in the Royal Navy." },
            { question: "MYTH or FACT: The British successfully burned the White House during the War of 1812.", isFact: true, explanation: "FACT: In 1814, British forces captured Washington D.C. and set fire to the White House and the Capitol building." }
        ],
        unit3: [
            { question: "MYTH or FACT: Manifest Destiny was an official law passed by Congress to force expansion.", isFact: false, explanation: "MYTH: It was not a law, but a widely held cultural belief that Americans were divinely ordained by God to settle the entire North American continent." },
            { question: "MYTH or FACT: The Trail of Tears was a voluntary migration by Native Americans seeking better land.", isFact: false, explanation: "MYTH: It was a brutal, forced relocation enacted by the U.S. government under the Indian Removal Act, resulting in the deaths of thousands of indigenous people." },
            { question: "MYTH or FACT: The invention of the cotton gin led to a decrease in the use of enslaved labor.", isFact: false, explanation: "MYTH: The cotton gin made processing cotton so incredibly profitable that plantation owners rapidly expanded their operations, drastically increasing the demand for enslaved labor." },
            { question: "MYTH or FACT: The Industrial Revolution in the U.S. began primarily in the Southern states.", isFact: false, explanation: "MYTH: It began in the North, specifically New England, where fast-moving rivers powered textile mills. The South remained heavily focused on agrarian plantation farming." },
            { question: "MYTH or FACT: Andrew Jackson fully supported and enforced the Supreme Court's decision in Worcester v. Georgia.", isFact: false, explanation: "MYTH: Jackson blatantly ignored Chief Justice John Marshall's ruling that protected Cherokee sovereignty, allowing the state of Georgia to proceed with forced removal." },
            { question: "MYTH or FACT: The Erie Canal was a massive financial failure.", isFact: false, explanation: "MYTH: It was an incredible success. It drastically lowered the cost of shipping goods between the Midwest and New York, booming the economy." },
            { question: "MYTH or FACT: The 'Spoils System' meant Jackson gave government jobs only to the most highly educated experts.", isFact: false, explanation: "MYTH: Jackson fired many experienced workers and replaced them with his own political supporters and friends, regardless of their qualifications." },
            { question: "MYTH or FACT: The Nullification Crisis was about South Carolina threatening to secede over high tariffs.", isFact: true, explanation: "FACT: Led by John C. Calhoun, South Carolina claimed it had the states' right to nullify the 'Tariff of Abominations,' nearly triggering a civil war." },
            { question: "MYTH or FACT: The Market Revolution meant people stopped farming entirely.", isFact: false, explanation: "MYTH: Farming continued, but instead of growing food just to survive, farmers began growing cash crops to sell in distant markets, using cash to buy manufactured goods." },
            { question: "MYTH or FACT: Andrew Jackson vetoed the National Bank because he thought it gave too much power to wealthy elites.", isFact: true, explanation: "FACT: Jackson waged a 'Bank War,' believing the institution was unconstitutional and favored rich investors at the expense of the common man." }
        ],
        unit4: [
            { question: "MYTH or FACT: The Underground Railroad was a literal train system running under the soil.", isFact: false, explanation: "MYTH: It was a metaphor. It was actually a highly organized, secret network of safe houses, guides (conductors), and routes used to help enslaved people escape to freedom." },
            { question: "MYTH or FACT: The Seneca Falls Convention of 1848 immediately granted women the right to vote.", isFact: false, explanation: "MYTH: It was the launching point of the movement. Women would not secure the national right to vote until the 19th Amendment was ratified 72 years later." },
            { question: "MYTH or FACT: Most people in the Northern states before the Civil War were radical abolitionists.", isFact: false, explanation: "MYTH: Radical abolitionists who wanted to end slavery immediately were a minority. Most Northerners were either indifferent or simply wanted to stop the *expansion* of slavery into new territories." },
            { question: "MYTH or FACT: The Second Great Awakening inspired many Americans to try to fix social problems.", isFact: true, explanation: "FACT: The religious revival taught that individuals had free will and a moral duty to improve society, fueling movements like abolition and temperance." },
            { question: "MYTH or FACT: Dorothea Dix's reform movement focused on building more factories.", isFact: false, explanation: "MYTH: Dix devoted her life to investigating and exposing the horrific conditions in prisons and mental asylums, successfully lobbying for humane hospitals." },
            { question: "MYTH or FACT: William Lloyd Garrison believed the Constitution was a great anti-slavery document.", isFact: false, explanation: "MYTH: Garrison, a radical abolitionist, believed the Constitution was a pro-slavery agreement with the devil and famously burned a copy of it in protest." },
            { question: "MYTH or FACT: Harriet Beecher Stowe's book 'Uncle Tom's Cabin' was widely loved in the South.", isFact: false, explanation: "MYTH: It was banned and burned in the South. It angered Southerners who claimed it was a lie, while it deeply moved Northerners against the horrors of slavery." },
            { question: "MYTH or FACT: The Temperance Movement was an effort to ban the consumption of alcohol.", isFact: true, explanation: "FACT: Reformers believed alcohol was the root cause of poverty, crime, and domestic violence, and they pushed heavily for prohibition laws." },
            { question: "MYTH or FACT: Frederick Douglass was an educated white Northerner who opposed slavery.", isFact: false, explanation: "MYTH: Douglass was a formerly enslaved man who escaped to the North, taught himself to read, and became one of the most brilliant and famous abolitionist speakers." },
            { question: "MYTH or FACT: The Declaration of Sentiments was modeled after the Declaration of Independence.", isFact: true, explanation: "FACT: Elizabeth Cady Stanton deliberately used the language of the founding document ('all men and women are created equal') to argue for women's rights." }
        ],
        unit5: [
            { question: "MYTH or FACT: The Dred Scott Supreme Court decision ruled that enslaved people were property, not citizens.", isFact: true, explanation: "FACT: The 1857 ruling was a massive blow to the abolitionist movement, declaring that Black Americans had no constitutional rights and that Congress couldn't ban slavery in the territories." },
            { question: "MYTH or FACT: The Fugitive Slave Act of 1850 allowed accused runaways to testify in front of a jury.", isFact: false, explanation: "MYTH: Accused individuals were denied the right to a jury trial and could not testify. Furthermore, commissioners were paid more money to return a person to slavery than to set them free." },
            { question: "MYTH or FACT: The Emancipation Proclamation immediately freed every enslaved person in the United States.", isFact: false, explanation: "MYTH: It only freed enslaved people in the Confederate states that were currently in rebellion. It did not apply to border states that stayed in the Union." },
            { question: "MYTH or FACT: The primary cause of Southern secession was states' rights, not slavery.", isFact: false, explanation: "MYTH: While they used the argument of 'states' rights', their own secession documents explicitly stated that the primary right they were fighting to protect was the institution of slavery." },
            { question: "MYTH or FACT: The Civil War began when the Union army invaded Richmond, Virginia.", isFact: false, explanation: "MYTH: The war officially began when Confederate forces fired upon Fort Sumter, a federal outpost in the harbor of Charleston, South Carolina." },
            { question: "MYTH or FACT: Abraham Lincoln won the 1860 election without a single electoral vote from the South.", isFact: true, explanation: "FACT: He wasn't even on the ballot in most Southern states. His election proved to the South that they had lost their national political power, sparking secession." },
            { question: "MYTH or FACT: 'Bleeding Kansas' occurred because of a dispute over building a railroad.", isFact: false, explanation: "MYTH: It was a violent mini-civil war triggered by the Kansas-Nebraska Act, which allowed settlers to vote on whether the territory would allow slavery (popular sovereignty)." },
            { question: "MYTH or FACT: The Battle of Gettysburg was a massive victory for the Confederacy.", isFact: false, explanation: "MYTH: It was a devastating defeat for Robert E. Lee that destroyed a huge portion of his army and permanently ended his invasions of the North." },
            { question: "MYTH or FACT: John Brown's raid on Harper's Ferry successfully started a massive slave rebellion.", isFact: false, explanation: "MYTH: The raid was a military failure, and Brown was captured and executed. However, it terrified the South and pushed the nation closer to war." },
            { question: "MYTH or FACT: Louisiana was strategically unimportant during the Civil War.", isFact: false, explanation: "MYTH: Because it controlled the mouth of the Mississippi River, New Orleans was the most vital port in the South, making it a primary target for the Union navy." }
        ]
    }
};