const gameQuestions = {
    EASY: {
        grade6: {
            unit1: [
                { question: "Which European power primarily sought land claims in North America for the fur trade?", choices: ["Spain", "England", "France", "Netherlands"], answer: 2, hint: "They built strong alliances with Native Americans to trade animal pelts.", dok: 1 },
                { question: "What was the first permanent English settlement in North America, founded in 1607?", choices: ["Plymouth", "Jamestown", "Roanoke", "Boston"], answer: 1, hint: "It was located in present-day Virginia and saved by tobacco.", dok: 1 },
                { question: "Which document, signed in 1620, was an early agreement for self-government by the Pilgrims?", choices: ["The Magna Carta", "The Mayflower Compact", "The Declaration of Independence", "The English Bill of Rights"], answer: 1, hint: "It was signed on their ship before landing at Plymouth.", dok: 1 },
                { question: "Who was the Native American who helped the Plymouth colonists survive by teaching them to farm?", choices: ["Pocahontas", "Chief Massasoit", "Squanto", "Metacom"], answer: 2, hint: "He acted as an interpreter and showed them how to use fish as fertilizer.", dok: 1 },
                { question: "Which religious group founded the Massachusetts Bay Colony to escape persecution in England?", choices: ["The Quakers", "The Puritans", "The Catholics", "The Pilgrims"], answer: 1, hint: "They wanted to 'purify' the Church of England.", dok: 1 }
            ],
            unit2: [
                { question: "Which colonial region's economy was heavily based on shipbuilding, fishing, and trade?", choices: ["The Middle Colonies", "The Southern Colonies", "The New England Colonies", "The Western Frontier"], answer: 2, hint: "They had rocky soil and short growing seasons.", dok: 1 },
                { question: "What was the horrific journey of enslaved Africans across the Atlantic Ocean called?", choices: ["The Columbian Exchange", "The Middle Passage", "The Northwest Passage", "The Great Migration"], answer: 1, hint: "It was the middle leg of the Triangular Trade route.", dok: 1 },
                { question: "Which religious group, known for pacifism and equality, settled in Pennsylvania?", choices: ["The Puritans", "The Pilgrims", "The Quakers", "The Anglicans"], answer: 2, hint: "They were led by William Penn.", dok: 1 },
                { question: "What were the large farms in the Southern colonies that relied on enslaved labor called?", choices: ["Plantations", "Granges", "Homesteads", "Manors"], answer: 0, hint: "They grew cash crops like tobacco and rice.", dok: 1 },
                { question: "A person who agreed to work for a set time in exchange for passage to the colonies was an...", choices: ["Enslaved person", "Indentured servant", "Apprentice", "Artisan"], answer: 1, hint: "They signed a contract, usually for 4 to 7 years.", dok: 1 }
            ],
            unit3: [
                { question: "Who is considered the 'Father of Louisiana' and founded New Orleans in 1718?", choices: ["John Law", "Alejandro O'Reilly", "Jean-Baptiste Le Moyne de Bienville", "Robert Cavelier de La Salle"], answer: 2, hint: "He served as governor of the colony multiple times.", dok: 1 },
                { question: "What was the set of laws created by the French to govern the lives of enslaved people?", choices: ["The Code Noir", "The Napoleonic Code", "The Bill of Rights", "The Magna Carta"], answer: 0, hint: "It translates to the 'Black Code'.", dok: 1 },
                { question: "Which group of exiles from Canada settled in Louisiana and became known as Cajuns?", choices: ["The Isleños", "The Acadians", "The Germans", "The Haitians"], answer: 1, hint: "They were expelled from Nova Scotia by the British.", dok: 1 },
                { question: "What is the oldest permanent European settlement in the Louisiana Purchase territory?", choices: ["New Orleans", "Baton Rouge", "Natchitoches", "Lafayette"], answer: 2, hint: "It was founded in 1714 as a trade outpost.", dok: 1 },
                { question: "Which Spanish governor earned a 'Bloody' nickname for crushing the 1768 rebellion?", choices: ["Bernardo de Galvez", "Antonio de Ulloa", "Alejandro O'Reilly", "Esteban Miro"], answer: 2, hint: "He firmly established Spanish authority in the colony.", dok: 1 }
            ],
            unit4: [
                { question: "The French and Indian War was fought primarily between France and which other European power?", choices: ["Spain", "Great Britain", "The Netherlands", "Portugal"], answer: 1, hint: "They were fighting for control of the Ohio River Valley.", dok: 1 },
                { question: "Which British act placed a tax on all paper goods, such as newspapers and legal documents?", choices: ["The Sugar Act", "The Quartering Act", "The Tea Act", "The Stamp Act"], answer: 3, hint: "Colonists had to buy a special seal to prove they paid.", dok: 1 },
                { question: "Who was the primary author of the Declaration of Independence?", choices: ["George Washington", "John Adams", "Thomas Jefferson", "Benjamin Franklin"], answer: 2, hint: "He wrote that 'all men are created equal.'", dok: 1 },
                { question: "What event involved the Sons of Liberty dumping taxed goods into the harbor?", choices: ["The Boston Massacre", "The Boston Tea Party", "The First Continental Congress", "The Battle of Bunker Hill"], answer: 1, hint: "They disguised themselves as Native Americans during the protest.", dok: 1 },
                { question: "Where did the British army surrender to George Washington, ending the Revolutionary War?", choices: ["Saratoga", "Lexington", "Yorktown", "Valley Forge"], answer: 2, hint: "General Cornwallis was trapped by the American army and French navy.", dok: 1 }
            ]
        },
        grade7: {
            unit1: [
                { question: "Who was the first President of the United States?", choices: ["John Adams", "Thomas Jefferson", "George Washington", "Alexander Hamilton"], answer: 2, hint: "He set many precedents, including leaving after two terms.", dok: 1 },
                { question: "Which leader of the Federalist Party served as the first Secretary of the Treasury?", choices: ["James Madison", "Thomas Jefferson", "Aaron Burr", "Alexander Hamilton"], answer: 3, hint: "He is featured on the ten-dollar bill.", dok: 1 },
                { question: "What was the 1794 uprising of farmers protesting a federal tax called?", choices: ["Shays' Rebellion", "Bacon's Rebellion", "The Whiskey Rebellion", "The Stamp Act Protest"], answer: 2, hint: "George Washington led troops to stop it.", dok: 1 },
                { question: "What did George Washington warn against in his Farewell Address?", choices: ["A strong national military", "Political parties and foreign alliances", "Westward expansion", "The creation of public schools"], answer: 1, hint: "He feared these would divide and endanger the young nation.", dok: 1 },
                { question: "The Alien and Sedition Acts, passed under John Adams, heavily restricted what freedom?", choices: ["Freedom of religion", "The right to bear arms", "Freedom of speech and the press", "The right to a speedy trial"], answer: 2, hint: "They made it illegal to criticize the government.", dok: 1 }
            ],
            unit2: [
                { question: "What 1803 land deal with France doubled the size of the United States?", choices: ["The Gadsden Purchase", "The Florida Purchase", "The Louisiana Purchase", "The Oregon Treaty"], answer: 2, hint: "It was purchased by Thomas Jefferson.", dok: 1 },
                { question: "Who did Thomas Jefferson send to explore the new western territory?", choices: ["Pike and Long", "Marquette and Joliet", "Lewis and Clark", "Boone and Crockett"], answer: 2, hint: "Their group was called the Corps of Discovery.", dok: 1 },
                { question: "What was the British practice of forcing American sailors to serve in their navy called?", choices: ["Blockading", "Impressment", "Embargo", "Conscription"], answer: 1, hint: "This was a major cause of the War of 1812.", dok: 1 },
                { question: "Who wrote 'The Star-Spangled Banner' after witnessing the attack on Fort McHenry?", choices: ["Francis Scott Key", "Thomas Jefferson", "Andrew Jackson", "James Madison"], answer: 0, hint: "He saw that the flag was still there in the morning.", dok: 1 },
                { question: "What battle made Andrew Jackson a national hero, even though the peace treaty was already signed?", choices: ["Battle of Lake Erie", "Battle of Tippecanoe", "Battle of New Orleans", "Battle of Yorktown"], answer: 2, hint: "He defended the mouth of the Mississippi River.", dok: 1 }
            ],
            unit3: [
                { question: "What foreign policy statement warned Europe not to colonize the Americas?", choices: ["The Truman Doctrine", "The Monroe Doctrine", "Manifest Destiny", "The American System"], answer: 1, hint: "It was issued in 1823 by the 5th president.", dok: 1 },
                { question: "The belief that the U.S. was meant to expand to the Pacific Ocean was known as...", choices: ["Imperialism", "Nationalism", "Manifest Destiny", "Sectionalism"], answer: 2, hint: "It translates to 'obvious fate'.", dok: 1 },
                { question: "What invention by Eli Whitney vastly increased the demand for enslaved labor in the South?", choices: ["The Steam Engine", "The Telegraph", "The Cotton Gin", "The Mechanical Reaper"], answer: 2, hint: "It quickly separated seeds from the fiber.", dok: 1 },
                { question: "The forced march of the Cherokee people to Indian Territory is tragically known as the...", choices: ["Trail of Tears", "Long Walk", "Great Migration", "Western Journey"], answer: 0, hint: "Thousands died due to exposure and disease.", dok: 1 },
                { question: "The rapid shift to machine-made goods in factories is known as the...", choices: ["Agricultural Revolution", "Industrial Revolution", "Information Age", "Progressive Era"], answer: 1, hint: "It began in New England with textile mills.", dok: 1 }
            ],
            unit4: [
                { question: "What was the first public meeting focused on women's rights in the U.S.?", choices: ["The Albany Congress", "The Boston Tea Party", "The Seneca Falls Convention", "The Constitutional Convention"], answer: 2, hint: "It was held in New York in 1848.", dok: 1 },
                { question: "Who was the famous 'conductor' on the Underground Railroad who never lost a passenger?", choices: ["Sojourner Truth", "Harriet Tubman", "Dorothea Dix", "Elizabeth Cady Stanton"], answer: 1, hint: "She was known as 'Moses' to her people.", dok: 1 },
                { question: "Which reformer campaigned to improve conditions in prisons and mental asylums?", choices: ["Horace Mann", "William Lloyd Garrison", "Dorothea Dix", "Frederick Douglass"], answer: 2, hint: "She convinced legislatures to build humane hospitals.", dok: 1 },
                { question: "What book by Harriet Beecher Stowe exposed the cruelty of slavery to Northern readers?", choices: ["Common Sense", "The Liberator", "Uncle Tom's Cabin", "The North Star"], answer: 2, hint: "Lincoln supposedly said it started the great war.", dok: 1 },
                { question: "Which Supreme Court case ruled that enslaved people were property and could not sue in court?", choices: ["Marbury v. Madison", "Worcester v. Georgia", "Dred Scott v. Sandford", "Plessy v. Ferguson"], answer: 2, hint: "It declared the Missouri Compromise unconstitutional.", dok: 1 }
            ]
        },
        grade8: {
            unit1: [
                { question: "African Americans who migrated from the South to Kansas after Reconstruction were called...", choices: ["Forty-niners", "Exodusters", "Sooners", "Muckrakers"], answer: 1, hint: "They sought to escape the Jim Crow South.", dok: 1 },
                { question: "What 1876 battle was a major victory for the Lakota and Cheyenne over Custer's cavalry?", choices: ["Battle of Wounded Knee", "Battle of the Alamo", "Battle of Little Bighorn", "Battle of Gettysburg"], answer: 2, hint: "It is also known as 'Custer's Last Stand'.", dok: 1 },
                { question: "The system of laws that enforced racial segregation in the South was known as...", choices: ["The Black Codes", "The Jim Crow system", "The Spoils System", "The American System"], answer: 1, hint: "It mandated separate facilities for whites and Blacks.", dok: 1 },
                { question: "Who founded the Tuskegee Institute and promoted vocational education for African Americans?", choices: ["W.E.B. Du Bois", "Ida B. Wells", "Booker T. Washington", "Marcus Garvey"], answer: 2, hint: "He believed economic skills should precede political equality.", dok: 1 },
                { question: "Which Supreme Court case established the 'separate but equal' doctrine in 1896?", choices: ["Dred Scott v. Sandford", "Plessy v. Ferguson", "Brown v. Board of Education", "Marbury v. Madison"], answer: 1, hint: "It legalized segregation for over 50 years.", dok: 1 }
            ],
            unit2: [
                { question: "What economic system is based on private ownership and competition in a free market?", choices: ["Communism", "Socialism", "Capitalism", "Mercantilism"], answer: 2, hint: "It drove the American Industrial Revolution.", dok: 1 },
                { question: "Which industrialist built a massive monopoly in the American steel industry?", choices: ["John D. Rockefeller", "Andrew Carnegie", "J.P. Morgan", "Cornelius Vanderbilt"], answer: 1, hint: "He used the Bessemer process and vertical integration.", dok: 1 },
                { question: "Journalists who investigated and exposed corruption and social problems were called...", choices: ["Robber Barons", "Muckrakers", "Populists", "Suffragettes"], answer: 1, hint: "Upton Sinclair and Ida Tarbell were famous examples.", dok: 1 },
                { question: "What was the political movement formed by farmers to fight back against big business and railroads?", choices: ["The Progressive Movement", "The Federalist Party", "The Populist Party", "The Whig Party"], answer: 2, hint: "Also known as the People's Party.", dok: 1 },
                { question: "The growth of cities, primarily due to industrialization and immigration, is called...", choices: ["Urbanization", "Assimilation", "Manifest Destiny", "Isolationism"], answer: 0, hint: "It led to overcrowded tenements and sanitation issues.", dok: 1 }
            ],
            unit3: [
                { question: "What 1898 war resulted in the U.S. acquiring Puerto Rico, Guam, and the Philippines?", choices: ["World War I", "The Mexican-American War", "The Spanish-American War", "The Civil War"], answer: 2, hint: "The sinking of the USS Maine helped trigger it.", dok: 1 },
                { question: "What man-made waterway connected the Atlantic and Pacific Oceans, drastically cutting travel time?", choices: ["The Suez Canal", "The Erie Canal", "The Panama Canal", "The Great Lakes Seaway"], answer: 2, hint: "President Theodore Roosevelt pushed for its construction.", dok: 1 },
                { question: "The sinking of which British passenger ship by a German U-boat outraged Americans in 1915?", choices: ["The Titanic", "The Maine", "The Lusitania", "The Arizona"], answer: 2, hint: "Over 100 Americans were killed.", dok: 1 },
                { question: "What was the primary style of fighting on the Western Front during World War I?", choices: ["Naval blockades", "Trench warfare", "Guerilla tactics", "Aerial bombing"], answer: 1, hint: "Soldiers lived in muddy ditches, causing a long stalemate.", dok: 1 },
                { question: "Which amendment, ratified in 1920, guaranteed women the right to vote?", choices: ["13th Amendment", "17th Amendment", "18th Amendment", "19th Amendment"], answer: 3, hint: "It was the culmination of the suffrage movement.", dok: 1 }
            ],
            unit4: [
                { question: "What era was defined by the 18th Amendment, which banned the manufacture and sale of alcohol?", choices: ["The Great Depression", "The Progressive Era", "Prohibition", "The Cold War"], answer: 2, hint: "It led to speakeasies and bootleggers.", dok: 1 },
                { question: "What was the 1920s cultural movement that celebrated African American art, music, and literature?", choices: ["The Great Awakening", "The Enlightenment", "The Harlem Renaissance", "The Second Great Migration"], answer: 2, hint: "It featured artists like Langston Hughes and Louis Armstrong.", dok: 1 },
                { question: "What severe environmental disaster devastated the Great Plains in the 1930s?", choices: ["The Great Flood", "The Dust Bowl", "The San Francisco Earthquake", "The Spanish Flu"], answer: 1, hint: "It was caused by drought and poor farming practices.", dok: 1 },
                { question: "What was the name of President Franklin D. Roosevelt's program to combat the Great Depression?", choices: ["The Square Deal", "The New Frontier", "The Great Society", "The New Deal"], answer: 3, hint: "It included programs like the CCC and TVA.", dok: 1 },
                { question: "Which controversial Louisiana governor and senator created the 'Share Our Wealth' program?", choices: ["Huey Long", "Jimmie Davis", "Edwin Edwards", "John McKeithen"], answer: 0, hint: "He was known as 'The Kingfish.'", dok: 1 }
            ]
        }
    },
    HARD: {
        grade6: {
            unit1: [
                { question: "Analyze the primary difference in motivation between the founding of Jamestown and Plymouth.", choices: ["Jamestown was for religion; Plymouth for profit.", "Jamestown was for profit; Plymouth for religious freedom.", "Both were founded primarily for military defense.", "Both were founded to find the Northwest Passage."], answer: 1, hint: "One was an investment company; the other was settled by Separatists.", dok: 3 },
                { question: "Evaluate the impact of Bacon's Rebellion on the labor system in the Virginia colony.", choices: ["It ended all farming in the region.", "It caused a shift from indentured servitude to enslaved African labor.", "It resulted in equal rights for poor farmers.", "It stopped the colony from expanding westward."], answer: 1, hint: "Wealthy planters began to fear uprisings from poor white servants.", dok: 4 },
                { question: "Explain how the geography of the New England colonies shaped their economic development.", choices: ["Rich soil led to large tobacco plantations.", "Rocky soil and natural harbors led to an economy based on fishing and shipbuilding.", "The warm climate allowed for year-round farming of cash crops.", "The lack of rivers prevented any trade networks from forming."], answer: 1, hint: "Since they couldn't farm on a large scale, they turned to the sea.", dok: 3 },
                { question: "Compare the French and English approaches to interacting with Native American populations.", choices: ["Both sought to conquer and enslave all tribes immediately.", "The French focused on trade alliances; the English focused on land acquisition and settlement.", "The English focused on trade alliances; the French focused on land acquisition.", "Neither group interacted with Native Americans at all."], answer: 1, hint: "France needed partners for the fur trade; England needed space for farms.", dok: 3 },
                { question: "Analyze the consequences of King Philip's War for Native Americans in New England.", choices: ["It resulted in the return of all tribal lands.", "It led to a lasting, peaceful treaty.", "It broke Native American power and allowed rapid colonial expansion.", "It had no significant impact on the region."], answer: 2, hint: "It was a devastating defeat that ended major indigenous resistance in the area.", dok: 3 }
            ],
            unit2: [
                { question: "Analyze the impact of the Triangular Trade on the continent of Africa.", choices: ["It increased the wealth and stability of all African nations.", "It led to depopulation, the loss of able-bodied workers, and increased warfare.", "It created a long-lasting era of peace between coastal tribes.", "It had no significant cultural or demographic impact."], answer: 1, hint: "The demand for enslaved people fueled conflict and societal collapse.", dok: 4 },
                { question: "Evaluate the role of town meetings in the development of colonial New England society.", choices: ["They established the absolute rule of the English King.", "They were exclusive clubs only for the wealthy elite.", "They served as an early form of direct democracy where citizens voted on local issues.", "They were used primarily to organize the militia."], answer: 2, hint: "It allowed ordinary community members to have a voice in local laws.", dok: 3 },
                { question: "Synthesize the reasons why the Middle Colonies were more culturally and religiously diverse than New England.", choices: ["New England legally banned all immigration.", "The Middle Colonies, particularly Pennsylvania, actively promoted religious tolerance.", "The Middle Colonies lacked any formal government structure.", "New England was geographically too difficult for ships to reach."], answer: 1, hint: "Consider the influence of Quaker beliefs on colonial policies.", dok: 3 },
                { question: "Analyze the economic interdependence between the Northern and Southern colonies.", choices: ["They functioned independently and did not trade with each other.", "The South grew food primarily to feed the North.", "The North relied on Southern cash crops to fuel its shipping and processing industries.", "The North provided all the agricultural labor for the South."], answer: 2, hint: "Northern merchants made vast fortunes shipping Southern tobacco and rice.", dok: 3 },
                { question: "Explain the fundamental difference between an indentured servant and an enslaved person in colonial law.", choices: ["Both were considered property for life.", "Servants worked under a temporary contract; enslaved people were considered property for life.", "Enslaved people worked under contracts; servants were property.", "Servants were paid high wages; enslaved people were paid low wages."], answer: 1, hint: "One condition was legally temporary; the other was permanent and hereditary.", dok: 3 }
            ],
            unit3: [
                { question: "Analyze the economic impact of John Law's 'Mississippi Bubble' on the Louisiana colony.", choices: ["It created lasting, stable wealth for all settlers.", "It led to a massive influx of settlers but ultimately resulted in a financial collapse.", "It had no significant impact on the colony's population or economy.", "It successfully paid off all of France's national debt."], answer: 1, hint: "While the financial scheme burst, it did succeed in bringing people to the colony.", dok: 4 },
                { question: "Evaluate the dual purpose of the French Code Noir in colonial Louisiana.", choices: ["It granted enslaved people full rights and banned religion.", "It established a strict legal framework for control while also mandating Catholic instruction.", "It abolished slavery and established free trade.", "It gave the Gens de Couleur Libres the right to vote."], answer: 1, hint: "It was a tool for subjugation that also included religious requirements.", dok: 4 },
                { question: "Compare the French and Spanish approaches to governing the Louisiana colony.", choices: ["The French maintained strict military control; the Spanish allowed self-rule.", "Both nations completely neglected the colony's administration.", "The French focused primarily on trade; the Spanish focused on order, administration, and military defense.", "The Spanish forced all colonists to adopt the Spanish language and customs immediately."], answer: 2, hint: "Think of Alejandro O'Reilly's actions to establish strong authority.", dok: 3 },
                { question: "Analyze the social significance of the 'Gens de Couleur Libres' in New Orleans.", choices: ["They were entirely prohibited from owning property.", "They formed a distinct, influential middle class of artisans, militia members, and property owners.", "They were primarily forced to work as field laborers.", "They held all the top political offices in the Spanish government."], answer: 1, hint: "They occupied a unique space in society between white colonists and enslaved Africans.", dok: 3 },
                { question: "Explain the strategic reasons behind the secret Treaty of Fontainebleau (1762).", choices: ["France sold Louisiana to Spain to pay off a massive debt.", "France transferred Louisiana to Spain to keep it out of British hands at the end of the war.", "Spain threatened to invade France if they didn't surrender the territory.", "The colonists successfully petitioned to join the Spanish Empire."], answer: 1, hint: "France knew they were losing the French and Indian War and wanted to protect their ally.", dok: 3 }
            ],
            unit4: [
                { question: "Analyze how the conclusion of the French and Indian War directly led to the American Revolution.", choices: ["It caused the colonists to ally with France against Britain.", "Britain's massive war debt led to the end of Salutary Neglect and the imposition of new taxes.", "The colonies gained so much land they decided they didn't need Britain.", "Native American tribes forced the British to grant the colonies independence."], answer: 1, hint: "The British felt the colonists should pay for their own defense.", dok: 4 },
                { question: "Evaluate the effectiveness of colonial boycotts against British taxation.", choices: ["They were completely ignored by the British Parliament.", "They caused severe economic pain for British merchants, leading to the repeal of several acts.", "They led directly to an immediate declaration of war.", "They only damaged the economy of the American colonies."], answer: 1, hint: "Hitting the British in their wallets proved to be a highly effective political weapon.", dok: 4 },
                { question: "Explain the constitutional argument behind the phrase 'Taxation without Representation'.", choices: ["Colonists refused to pay any taxes under any circumstances.", "Colonists believed only their own elected colonial assemblies possessed the legal right to tax them.", "Colonists demanded seats in the French Parliament.", "Colonists wanted the King to collect taxes personally."], answer: 1, hint: "It was about *who* had the authority to levy the tax, not just the money itself.", dok: 3 },
                { question: "Synthesize the main arguments presented by Thomas Paine in his pamphlet 'Common Sense'.", choices: ["Monarchy is an irrational system and it is illogical for an island to rule a continent.", "The colonies should remain loyal to the King but demand lower taxes.", "Taxes are necessary for protection and should be paid willingly.", "France is the true enemy of American liberty."], answer: 0, hint: "He used plain language to argue that independence was the only logical choice.", dok: 3 },
                { question: "Analyze the strategic importance of the Battle of Saratoga in the Revolutionary War.", choices: ["It allowed the British to successfully capture New York City.", "It proved the Continental Army could fight and secured a vital military alliance with France.", "It was the final battle that ended the conflict.", "It resulted in the devastating capture of George Washington."], answer: 1, hint: "Without the financial and naval support gained from this victory, the Americans likely would have lost.", dok: 4 }
            ]
        },
        grade7: {
            unit1: [
                { question: "Analyze how the differing philosophies of Alexander Hamilton and Thomas Jefferson laid the groundwork for the first political parties.", choices: ["Their agreement on foreign policy united the nation.", "Their fundamental disagreements on the scope of federal power and the economy created factional divides.", "Both leaders advocated for a weak central government, uniting voters.", "Their personal rivalry was the sole cause of the divisions."], answer: 1, hint: "Consider their contrasting visions of an industrial vs. agrarian society.", dok: 4 },
                { question: "Evaluate the significance of George Washington's response to the Whiskey Rebellion.", choices: ["It exposed the crippling weakness of the federal government.", "It proved the new constitutional government had the power and will to enforce its laws.", "It led to the immediate and permanent repeal of the federal tax.", "It caused several states to threaten secession from the Union."], answer: 1, hint: "Compare this decisive action to the government's inability to handle Shays' Rebellion.", dok: 4 },
                { question: "Explain how the Federalist defense of the National Bank relied on a 'loose construction' interpretation of the Constitution.", choices: ["They argued the Constitution explicitly mentioned a bank.", "They utilized the 'Necessary and Proper' clause to justify the bank's creation to manage the economy.", "They claimed the bank was unconstitutional but necessary anyway.", "They argued state banks should hold supreme authority."], answer: 1, hint: "They believed the government had implied powers not explicitly written in the text.", dok: 4 },
                { question: "Analyze the political consequences of the Alien and Sedition Acts passed under John Adams.", choices: ["They successfully unified the country against the threat of France.", "They were perceived as an unconstitutional attack on free speech and were used to jail political opponents.", "They were immediately struck down by the Supreme Court.", "They had no real political impact and were widely ignored."], answer: 1, hint: "How would a law that criminalizes government criticism affect a democracy?", dok: 3 },
                { question: "Evaluate the long-term historical impact of the Election of 1800 (the 'Revolution of 1800').", choices: ["It proved that power could not be transferred peacefully between opposing parties.", "It resulted in the dissolution of the Electoral College.", "It established the crucial precedent of a peaceful transfer of power between rival political factions.", "It led to a constitutional crisis that permanently weakened the presidency."], answer: 2, hint: "What did it mean for the stability of the Republic that the ruling party stepped down after losing?", dok: 4 }
            ],
            unit2: [
                { question: "Analyze the constitutional dilemma Thomas Jefferson faced regarding the Louisiana Purchase.", choices: ["He believed the purchase was explicitly authorized by the Constitution.", "He sought to pass a constitutional amendment before finalizing the treaty.", "He had to adopt a 'loose construction' interpretation of executive treaty-making powers to justify the purchase.", "He ignored the Constitution entirely and bypassed Congress."], answer: 2, hint: "As a strict constructionist, he struggled because the Constitution didn't explicitly grant the power to buy land.", dok: 4 },
                { question: "Evaluate the most significant long-term domestic consequence of the War of 1812 for the United States.", choices: ["The U.S. successfully annexed large portions of Canada.", "The war triggered a severe, decades-long economic depression.", "The war destroyed American manufacturing capabilities in New England.", "The war fostered a surge of nationalism and stimulated domestic industrial growth."], answer: 3, hint: "Cut off from British goods, Americans had to start making things themselves while feeling a new sense of pride.", dok: 4 },
                { question: "Compare the motivations of Native American groups who allied with Britain during the War of 1812 with those who allied with the U.S.", choices: ["All Native American groups universally allied with Britain.", "Tribes made strategic alliances based on preserving their land and sovereignty against expansion.", "All Native American groups remained strictly neutral.", "Motivations were based entirely on the fur trade."], answer: 1, hint: "Think about who represented the most immediate threat to indigenous lands at the time.", dok: 3 },
                { question: "Explain the psychological and political impact of the Battle of New Orleans.", choices: ["It was viewed as a minor skirmish with no real significance.", "Though fought after the peace treaty, it created massive national pride and propelled Jackson to political stardom.", "Jackson's defeat at the battle ruined his political career.", "It was seen as an embarrassing and unnecessary loss of life."], answer: 1, hint: "Focus on the symbolic importance of overwhelmingly defeating the British military.", dok: 3 },
                { question: "Synthesize how events like the West Florida Controversy demonstrated early American expansionist desires.", choices: ["They show the U.S. was hesitant to expand beyond its borders.", "They were isolated incidents orchestrated by the Spanish government.", "They reflected a clear, aggressive pattern of settlers pushing boundaries to solidify U.S. control of the Gulf Coast.", "They proved that diplomacy was always preferred over action."], answer: 2, hint: "Consider the actions of American settlers seizing forts in Spanish territory.", dok: 4 }
            ],
            unit3: [
                { question: "Analyze how the invention of the cotton gin contributed to the growth of sectionalism.", choices: ["It reduced the need for enslaved labor, bringing the North and South together politically.", "It made the Southern economy more industrial, mirroring the North.", "It deeply entrenched plantation agriculture and enslaved labor in the South while the North industrialized.", "It had no significant impact on the relationship between the two regions."], answer: 2, hint: "How did one invention reinforce two totally different economic systems?", dok: 4 },
                { question: "Evaluate President Andrew Jackson's response to the Supreme Court ruling in Worcester v. Georgia.", choices: ["He utilized the military to enforce the ruling and protect Cherokee lands.", "He openly defied the Court's authority, allowing the forced removal to proceed.", "He asked Congress to rewrite the Indian Removal Act.", "He resigned from office in protest of the decision."], answer: 1, hint: "He essentially said, 'John Marshall has made his decision; now let him enforce it.'", dok: 4 },
                { question: "Explain how the ideology of Manifest Destiny influenced U.S. actions regarding the Mexican-American War.", choices: ["It encouraged diplomacy to preserve peace at all costs.", "It provided a moral and divine justification for aggressive territorial expansion and war.", "It focused national attention solely on acquiring the Oregon Territory.", "It was used by opponents of the war to argue against expansion."], answer: 1, hint: "If a nation believes it is 'destined' by God to control the continent, how does it view obstacles?", dok: 3 },
                { question: "Analyze the economic impact of the Erie Canal and the Transportation Revolution.", choices: ["It made transportation slower and significantly more expensive.", "It connected the agricultural Midwest to Eastern markets, drastically lowering shipping costs and boosting trade.", "It primarily benefited only the state of New York.", "It caused a total collapse of the Southern economy."], answer: 1, hint: "Think about how moving goods efficiently by water changed the national economy.", dok: 3 },
                { question: "Synthesize the 'push' and 'pull' factors that drove massive Irish and German immigration in the 1840s.", choices: ["Immigrants were pushed by religious freedom and pulled by famine.", "Immigrants were pushed by famine and political turmoil, and pulled by the promise of jobs and land in the U.S.", "The only factor was the California Gold Rush.", "The U.S. government forced them to immigrate."], answer: 1, hint: "Connect disasters in Europe with opportunities in a growing America.", dok: 4 }
            ],
            unit4: [
                { question: "Analyze the significance of the language used in the 'Declaration of Sentiments' at the Seneca Falls Convention.", choices: ["It was written in French to appeal to international allies.", "By mimicking the Declaration of Independence, it effectively argued that women were entitled to the same foundational rights as men.", "It focused entirely on the abolition of slavery rather than women's rights.", "It was a legal contract to establish public schools."], answer: 1, hint: "Think about the phrase: 'We hold these truths to be self-evident: that all men and women are created equal.'", dok: 4 },
                { question: "Evaluate the impact of the Fugitive Slave Act of 1850 on Northern society.", choices: ["It made Northerners more sympathetic to Southern slaveholders.", "It outraged Northerners by forcing them to participate in the slave system, dramatically increasing anti-slavery sentiment.", "It completely stopped all escapes via the Underground Railroad.", "It peacefully resolved the tensions between the North and South."], answer: 1, hint: "It brought the brutal reality of slavery directly into free states.", dok: 4 },
                { question: "Explain how the concept of 'popular sovereignty' in the Kansas-Nebraska Act led to 'Bleeding Kansas.'", choices: ["It successfully banned slavery in the territory.", "By letting settlers vote on slavery, it triggered a violent rush of pro- and anti-slavery forces fighting to control the election.", "It forced all Native Americans to leave the territory.", "It resulted in a unanimous, peaceful vote."], answer: 1, hint: "When the people decide the law, extremes on both sides will try to rig the outcome.", dok: 3 },
                { question: "Analyze the core legal reasoning behind the Supreme Court's Dred Scott decision.", choices: ["The Court ruled Scott was free because he lived in a free state.", "The Court ruled that Black Americans were not citizens and that Congress had no constitutional authority to ban slavery in the territories.", "The Court ruled that slavery was illegal nationwide.", "The Court refused to hear the case entirely."], answer: 1, hint: "Chief Justice Taney's decision essentially declared the Missouri Compromise unconstitutional.", dok: 4 },
                { question: "Compare the approaches of abolitionists William Lloyd Garrison and Frederick Douglass.", choices: ["Both believed the Constitution was inherently pro-slavery.", "Garrison saw the Constitution as a pro-slavery document to be condemned, while Douglass believed its principles could be used to fight for freedom.", "Douglass advocated for violence, while Garrison strictly advocated for gradual political reform.", "Both focused exclusively on colonizing freed slaves in Africa."], answer: 1, hint: "One burned the document; the other cited its ideals.", dok: 4 }
            ]
        },
        grade8: {
            unit1: [
                { question: "Analyze the motivations of the 'Exodusters' migrating to the West in the late 1870s.", choices: ["They were seeking gold in the California mountains.", "They were fleeing the violence, disenfranchisement, and economic oppression of the Jim Crow South to find land and freedom.", "They were recruited by railroad companies to lay track.", "They were European immigrants seeking factory jobs."], answer: 1, hint: "Consider what was happening to African Americans in the South after Reconstruction ended.", dok: 3 },
                { question: "Evaluate the argument presented in Frederick Jackson Turner's 'Frontier Thesis'.", choices: ["He argued that the frontier was irrelevant to American history.", "He argued that the process of expanding the frontier shaped the unique American character of independence and democracy.", "He argued that the West should be returned to Native American control.", "He argued that industrial cities were the true source of American culture."], answer: 1, hint: "He believed facing the challenges of the wild made Americans who they are.", dok: 3 },
                { question: "Analyze the strategic and cultural impact of the near-extermination of the American buffalo.", choices: ["It allowed Native American tribes to develop new agricultural techniques.", "It was a deliberate tactic to subjugate Plains Indians by destroying their primary source of food, shelter, and cultural identity.", "It had no effect on the conflict between settlers and tribes.", "It was solely the result of a natural disease outbreak."], answer: 1, hint: "Without the buffalo, the nomadic lifestyle of the Plains tribes was impossible.", dok: 4 },
                { question: "Compare the philosophies of Booker T. Washington and W.E.B. Du Bois regarding civil rights.", choices: ["Both demanded immediate integration and voting rights.", "Washington prioritized economic self-reliance and vocational training, while Du Bois demanded immediate political equality and higher education.", "Du Bois focused on vocational training, while Washington founded the NAACP.", "Both believed African Americans should emigrate back to Africa."], answer: 1, hint: "Think of the 'Atlanta Compromise' versus the 'Talented Tenth'.", dok: 4 },
                { question: "Evaluate the long-term legal and social impact of the Plessy v. Ferguson decision.", choices: ["It immediately ended all segregation in the United States.", "It legitimized state-sponsored discrimination by establishing the 'separate but equal' doctrine, entrenching the Jim Crow system for decades.", "It applied only to railroad travel and had no broader impact.", "It guaranteed equal funding for all segregated public schools."], answer: 1, hint: "This ruling gave legal cover to systemic racism.", dok: 4 }
            ],
            unit2: [
                { question: "Analyze how the policy of 'laissez-faire' capitalism contributed to the rise of monopolies.", choices: ["It created strict labor laws that protected workers.", "It resulted in heavy taxation on large corporations.", "By minimizing government regulation, it allowed aggressive businessmen to eliminate competition and consolidate entire industries.", "It provided government subsidies exclusively to small family farms."], answer: 2, hint: "The term translates to 'let do' or 'hands off'.", dok: 3 },
                { question: "Evaluate the effectiveness of early labor unions in improving the lives of industrial workers.", choices: ["They immediately secured an 8-hour workday and high wages for all.", "Despite facing violent opposition and government intervention favoring owners, they laid the groundwork for future worker protections.", "They were entirely controlled by the factory owners.", "They focused solely on political elections rather than workplace conditions."], answer: 1, hint: "Strikes were often crushed, but the movement slowly brought attention to the issues.", dok: 4 },
                { question: "Explain the strategy of 'horizontal integration' used by industrialists like John D. Rockefeller.", choices: ["Owning every step of the supply chain, from raw materials to transport.", "Buying out or merging with all competing companies in the same industry to control the market.", "Refusing to use any new technological advancements.", "Paying workers high wages to ensure loyalty."], answer: 1, hint: "Think of expanding outward to absorb all your rivals.", dok: 3 },
                { question: "Analyze the role of 'muckrakers' in driving the reforms of the Progressive Era.", choices: ["They lobbied Congress to lower taxes on the wealthy.", "They used investigative journalism to expose corporate greed and societal rot, turning public opinion in favor of government regulation.", "They organized the construction of new factories.", "They promoted the expansion of American imperialism."], answer: 1, hint: "Their exposes on things like meatpacking forced the government to act.", dok: 4 },
                { question: "Synthesize the core grievances that led to the formation of the Populist Party.", choices: ["Wealthy bankers were angry about low interest rates.", "Urban factory workers wanted to ban all immigration.", "Farmers were drowning in debt, frustrated by high railroad shipping rates, and felt ignored by the major political parties.", "Southern planters wanted to expand slavery into the West."], answer: 2, hint: "The movement was rooted in the economic struggles of the agricultural working class.", dok: 4 }
            ],
            unit3: [
                { question: "Analyze the role of 'yellow journalism' in the outbreak of the Spanish-American War.", choices: ["It provided objective, balanced reporting that calmed public tensions.", "It deliberately sensationalized events like the sinking of the USS Maine to inflame public anger and push the government toward war.", "It focused entirely on domestic issues, ignoring the conflict in Cuba.", "It was a Spanish propaganda tool used to intimidate Americans."], answer: 1, hint: "Publishers like Hearst and Pulitzer used dramatic headlines to sell papers.", dok: 4 },
                { question: "Evaluate the strategic importance of the Panama Canal to American imperialism.", choices: ["It was built primarily as a tourist attraction.", "It vastly improved global trade efficiency and allowed the U.S. Navy to move quickly between oceans, projecting power globally.", "It was designed to protect Central America from European invasion.", "It severely damaged the U.S. economy due to construction costs."], answer: 1, hint: "Think about Theodore Roosevelt's 'Big Stick' diplomacy.", dok: 3 },
                { question: "Explain how the Zimmermann Telegram influenced the United States' entry into World War I.", choices: ["It was a plea for peace from the German government.", "It revealed a German plot to ally with Mexico and attack the U.S., shattering American neutrality.", "It proved that the British were illegally sinking American ships.", "It contained the designs for a new, devastating weapon."], answer: 1, hint: "It brought the threat of the European war directly to the American border.", dok: 3 },
                { question: "Analyze the purpose of the Espionage and Sedition Acts during World War I.", choices: ["To protect the free speech rights of anti-war protestors.", "To recruit more soldiers into the military.", "To silence dissent, prevent interference with the draft, and suppress criticism of the government's war effort.", "To expose German spies operating in Washington D.C."], answer: 2, hint: "The government argued that civil liberties could be restricted during wartime.", dok: 4 },
                { question: "Evaluate the reasons for the U.S. Senate's rejection of the Treaty of Versailles and the League of Nations.", choices: ["They believed the treaty was far too lenient on Germany.", "They feared that joining the League would surrender U.S. sovereignty and drag the nation into future European conflicts.", "President Wilson refused to sign the final document.", "The treaty did not grant the U.S. enough new territory."], answer: 1, hint: "Many senators wanted a return to the policy of isolationism.", dok: 4 }
            ],
            unit4: [
                { question: "Analyze the unintended consequences of the 18th Amendment (Prohibition).", choices: ["It successfully eliminated all alcohol consumption in the U.S.", "It led to a massive rise in organized crime, bootlegging, and a general disrespect for the law.", "It caused the immediate start of the Great Depression.", "It forced the closure of all movie theaters and jazz clubs."], answer: 1, hint: "Banning a popular product created a lucrative black market.", dok: 3 },
                { question: "Explain how the practice of 'buying on margin' contributed to the 1929 stock market crash.", choices: ["It meant the government heavily insured all stock purchases.", "It allowed investors to buy stocks with borrowed money, creating an artificial bubble that burst when prices dropped and loans were called in.", "It prevented ordinary citizens from investing in the market.", "It required buyers to use only gold to purchase stocks."], answer: 1, hint: "When the market dipped, people had to sell off everything to pay back their brokers.", dok: 4 },
                { question: "Evaluate the fundamental shift in the role of the federal government caused by the New Deal.", choices: ["The government withdrew completely from economic regulation.", "The government assumed unprecedented responsibility for the economic welfare of its citizens and the regulation of business.", "The government abolished the capitalist system entirely.", "The government focused solely on foreign policy and ignored domestic issues."], answer: 1, hint: "Programs like Social Security created a permanent 'safety net'.", dok: 4 },
                { question: "Analyze how human actions contributed to the environmental disaster of the Dust Bowl.", choices: ["Decades of deep plowing and over-farming removed the native grasses that held the soil in place, leaving it vulnerable to drought and wind.", "The construction of massive dams disrupted the natural water cycle of the plains.", "Excessive pollution from new urban factories poisoned the soil.", "The introduction of invasive species destroyed the local crops."], answer: 0, hint: "Farmers ignored traditional ecological balances in the pursuit of higher yields.", dok: 3 },
                { question: "Synthesize the political appeal of Huey Long in 1930s Louisiana.", choices: ["He appealed only to the wealthy elite and powerful corporations.", "He used populist rhetoric and his 'Share Our Wealth' program to appeal to the desperate, impoverished working class during the Depression.", "He promised to completely dismantle the state's infrastructure.", "He advocated for a return to the policies of the Gilded Age."], answer: 1, hint: "He promised to 'make every man a king' by heavily taxing the rich.", dok: 4 }
            ]
        }
    },
    SKIBIDI: {
        grade6: {
            unit1: [
                { question: "The first permanent English settlement in North America, founded in 1607, was ___.", answer: ["jamestown", "james town"], hint: "It is located in Virginia." },
                { question: "The Native American who helped the Pilgrims survive by teaching them to farm was ___.", answer: ["squanto", "tisquantum"], hint: "He spoke English and helped them use fish as fertilizer." },
                { question: "The agreement for self-government signed by the Pilgrims was the ___ Compact.", answer: ["mayflower"], hint: "Named after their ship." },
                { question: "The religious group that wanted to completely separate from the Church of England and founded Plymouth were the ___.", answer: ["pilgrims", "separatists"], hint: "They celebrated the first Thanksgiving." },
                { question: "The 1676 uprising of poor farmers in Virginia was known as ___ Rebellion.", answer: ["bacons", "bacon"], hint: "Led by a man named Nathaniel." }
            ],
            unit2: [
                { question: "The horrific journey of enslaved Africans across the Atlantic was called the ___ Passage.", answer: ["middle"], hint: "It was the center leg of the Triangular Trade." },
                { question: "William Penn founded Pennsylvania as a safe haven for a religious group known as the ___.", answer: ["quakers"], hint: "They believed in pacifism and equality." },
                { question: "Large agricultural estates in the South that relied on enslaved labor were called ___.", answer: ["plantations", "plantation"], hint: "They grew cash crops." },
                { question: "People who worked for a set number of years in exchange for passage to America were ___ servants.", answer: ["indentured"], hint: "They signed a temporary contract." },
                { question: "The region known for rocky soil, shipbuilding, and fishing was the ___ Colonies.", answer: ["new england"], hint: "It includes Massachusetts and Rhode Island." }
            ],
            unit3: [
                { question: "The 'Father of Louisiana' who founded New Orleans in 1718 is Jean-Baptiste Le Moyne de ___.", answer: ["bienville"], hint: "He was the brother of Iberville." },
                { question: "The set of laws governing the lives of enslaved people in French Louisiana was the Code ___.", answer: ["noir"], hint: "It means 'Black' in French." },
                { question: "The oldest permanent European settlement in Louisiana is ___.", answer: ["natchitoches"], hint: "It was founded in 1714." },
                { question: "The exiles from Canada who settled in Louisiana and developed a unique culture are the ___.", answer: ["acadians", "cajuns"], hint: "They were kicked out of Nova Scotia by the British." },
                { question: "The Spanish governor who crushed the 1768 rebellion earned the nickname 'Bloody' ___.", answer: ["oreilly", "o'reilly", "alejandro o'reilly"], hint: "He executed the leaders of the revolt." }
            ],
            unit4: [
                { question: "The war fought between Britain and France for control of North America was the ___ War.", answer: ["french and indian", "seven years"], hint: "It started in 1754." },
                { question: "The author of the Declaration of Independence was Thomas ___.", answer: ["jefferson"], hint: "He later became the 3rd President." },
                { question: "The first battles of the American Revolution were fought at Lexington and ___.", answer: ["concord"], hint: "It was the 'Shot Heard 'Round the World'." },
                { question: "The turning point battle that convinced France to ally with the Americans was the Battle of ___.", answer: ["saratoga"], hint: "It took place in New York." },
                { question: "The British general Cornwallis surrendered, effectively ending the war, at the Battle of ___.", answer: ["yorktown"], hint: "He was trapped on a peninsula in Virginia." }
            ]
        },
        grade7: {
            unit1: [
                { question: "The first President of the United States was George ___.", answer: ["washington"], hint: "He set the precedent of a two-term limit." },
                { question: "The leader of the Federalist Party and first Secretary of the Treasury was Alexander ___.", answer: ["hamilton"], hint: "He pushed for a National Bank." },
                { question: "The 1794 uprising of farmers protesting a federal tax was the ___ Rebellion.", answer: ["whiskey", "whiskeys"], hint: "Washington led troops to stop it." },
                { question: "The controversial laws passed by John Adams that limited free speech were the Alien and ___ Acts.", answer: ["sedition"], hint: "They targeted immigrants and government critics." },
                { question: "The diplomatic incident where French agents demanded a bribe from the U.S. was the ___ Affair.", answer: ["xyz"], hint: "It involved three unnamed agents." }
            ],
            unit2: [
                { question: "The land deal that doubled the size of the United States in 1803 was the ___ Purchase.", answer: ["louisiana"], hint: "Thomas Jefferson bought it from France." },
                { question: "The explorers sent by Jefferson to map the new western territory were ___ and Clark.", answer: ["lewis"], hint: "They were guided by Sacagawea." },
                { question: "The British practice of forcing American sailors into their navy is called ___.", answer: ["impressment"], hint: "It was a major cause of the War of 1812." },
                { question: "The national anthem, 'The Star-Spangled Banner,' was written by Francis Scott ___.", answer: ["key"], hint: "He watched the bombing of Fort McHenry." },
                { question: "The American general who became a hero at the Battle of New Orleans was Andrew ___.", answer: ["jackson"], hint: "He later became the 7th President." }
            ],
            unit3: [
                { question: "The belief that the U.S. was destined to expand to the Pacific Ocean is Manifest ___.", answer: ["destiny"], hint: "It means 'obvious fate'." },
                { question: "The forced removal of the Cherokee people to Indian Territory is known as the Trail of ___.", answer: ["tears"], hint: "Thousands died on this tragic journey." },
                { question: "The policy warning European nations to stay out of the Americas is the ___ Doctrine.", answer: ["monroe"], hint: "Issued in 1823." },
                { question: "The invention by Eli Whitney that vastly increased the demand for slavery was the ___ gin.", answer: ["cotton"], hint: "It separated seeds from fibers." },
                { question: "The man-made waterway connecting the Great Lakes to New York City is the ___ Canal.", answer: ["erie"], hint: "It revolutionized shipping." }
            ],
            unit4: [
                { question: "The first women's rights convention was held in 1848 at ___ Falls, New York.", answer: ["seneca"], hint: "They wrote the Declaration of Sentiments." },
                { question: "The famous conductor of the Underground Railroad was Harriet ___.", answer: ["tubman"], hint: "She was known as 'Moses'." },
                { question: "The author of the influential anti-slavery novel 'Uncle Tom's Cabin' was Harriet Beecher ___.", answer: ["stowe"], hint: "Her book angered the South." },
                { question: "The reformer who worked to improve prisons and mental asylums was Dorothea ___.", answer: ["dix"], hint: "She investigated terrible conditions in jails." },
                { question: "The Supreme Court case that ruled enslaved people were property, not citizens, was the ___ Scott decision.", answer: ["dred"], hint: "He sued for his freedom after living in free territory." }
            ]
        },
        grade8: {
            unit1: [
                { question: "African Americans who migrated to Kansas to escape the Jim Crow South were called ___.", answer: ["exodusters"], hint: "Their name references a biblical journey." },
                { question: "The 1876 battle known as 'Custer's Last Stand' was the Battle of Little ___.", answer: ["bighorn", "big horn"], hint: "A major victory for the Plains Indians." },
                { question: "The system of laws enforcing racial segregation in the South was called ___ Crow.", answer: ["jim"], hint: "Named after a minstrel show character." },
                { question: "The civil rights leader who co-founded the NAACP and demanded immediate equality was W.E.B. ___.", answer: ["dubois", "du bois"], hint: "He opposed Booker T. Washington's gradual approach." },
                { question: "The 1896 Supreme Court case that legalized 'separate but equal' segregation was Plessy v. ___.", answer: ["ferguson"], hint: "It upheld a Louisiana train car law." }
            ],
            unit2: [
                { question: "A company that has complete control over an entire industry is a ___.", answer: ["monopoly"], hint: "Standard Oil is a famous example." },
                { question: "Journalists who exposed corruption and social problems were known as ___.", answer: ["muckrakers", "muckraker"], hint: "Upton Sinclair was one." },
                { question: "The industrialist who built a monopoly in the American steel industry was Andrew ___.", answer: ["carnegie"], hint: "He used the Bessemer process." },
                { question: "The industrialist who created the Standard Oil trust was John D. ___.", answer: ["rockefeller"], hint: "He used horizontal integration." },
                { question: "The political party formed by farmers to fight big business was the ___ Party.", answer: ["populist", "peoples", "people's"], hint: "They wanted the free coinage of silver." }
            ],
            unit3: [
                { question: "The man-made waterway built to connect the Atlantic and Pacific oceans is the ___ Canal.", answer: ["panama"], hint: "Theodore Roosevelt championed its construction." },
                { question: "The 1898 conflict that made the U.S. a world power was the ___-American War.", answer: ["spanish"], hint: "Remember the Maine!" },
                { question: "The British passenger ship sunk by a German U-boat in 1915 was the ___.", answer: ["lusitania"], hint: "128 Americans died." },
                { question: "The secret message proposing an alliance between Germany and Mexico was the ___ Telegram.", answer: ["zimmermann", "zimmerman"], hint: "It pushed the U.S. into WWI." },
                { question: "The primary style of fighting on the Western Front in WWI was ___ warfare.", answer: ["trench"], hint: "Soldiers dug deep defensive networks." }
            ],
            unit4: [
                { question: "The era in which the manufacture and sale of alcohol was illegal was known as ___.", answer: ["prohibition"], hint: "It was established by the 18th Amendment." },
                { question: "The 1920s cultural movement celebrating African American art and music was the ___ Renaissance.", answer: ["harlem"], hint: "Located in a New York City neighborhood." },
                { question: "The severe environmental disaster of the 1930s on the Great Plains was the ___ Bowl.", answer: ["dust"], hint: "Caused by drought and over-farming." },
                { question: "President Franklin D. Roosevelt's program to combat the Great Depression was the New ___.", answer: ["deal"], hint: "It included Relief, Recovery, and Reform." },
                { question: "The populist Louisiana governor known for his 'Share Our Wealth' program was Huey ___.", answer: ["long"], hint: "His nickname was 'The Kingfish'." }
            ]
        }
    },
    MYTH: {
        grade6: {
            unit1: [
                { question: "MYTH or FACT: Christopher Columbus was the first European to reach North America.", isFact: false, explanation: "MYTH: Viking explorers, such as Leif Erikson, established settlements in North America nearly 500 years before Columbus sailed." },
                { question: "MYTH or FACT: The Pilgrims always wore black and white clothing with large buckles.", isFact: false, explanation: "MYTH: This is a 19th-century invention. Historical records show Pilgrims wore a variety of typical English colors like red, green, and brown." },
                { question: "MYTH or FACT: The House of Burgesses was the first representative assembly in the American colonies.", isFact: true, explanation: "FACT: Established in Jamestown in 1619, it allowed colonists to elect representatives, setting a crucial precedent for American democracy." },
                { question: "MYTH or FACT: Native American tribes had no concept of land use or territories before Europeans arrived.", isFact: false, explanation: "MYTH: While they did not buy and sell land as private property like Europeans, tribes had strict territorial boundaries and complex systems for hunting and farming rights." },
                { question: "MYTH or FACT: The Puritans established Massachusetts to create a society with total religious freedom for everyone.", isFact: false, explanation: "MYTH: The Puritans wanted freedom for *themselves*, but they were highly intolerant of other beliefs, famously banishing dissenters like Roger Williams and Anne Hutchinson." }
            ],
            unit2: [
                { question: "MYTH or FACT: Slavery existed in all 13 American colonies during the colonial period.", isFact: true, explanation: "FACT: While plantation slavery was most economically dominant in the Southern colonies, enslaved people were held and exploited in the Northern and Middle colonies as well." },
                { question: "MYTH or FACT: Indentured servants were legally considered slaves for the rest of their lives.", isFact: false, explanation: "MYTH: Indentured servants signed a contract to work for a specific period (usually 4 to 7 years) to pay off their travel debt, after which they were legally free." },
                { question: "MYTH or FACT: The Middle Colonies were the most culturally and religiously diverse region.", isFact: true, explanation: "FACT: Because colonies like Pennsylvania promoted religious tolerance, they attracted a wide variety of immigrants, including Germans, Dutch, and Scots-Irish." },
                { question: "MYTH or FACT: The New England colonies relied heavily on massive tobacco plantations.", isFact: false, explanation: "MYTH: New England's rocky soil and harsh winters made large-scale agriculture impossible. Their economy relied on fishing, whaling, shipbuilding, and trade." },
                { question: "MYTH or FACT: The Quakers believed in pacifism and the spiritual equality of all people.", isFact: true, explanation: "FACT: Because of their belief in the 'inner light' in everyone, Quakers were early advocates for fair treatment of Native Americans and the abolition of slavery." }
            ],
            unit3: [
                { question: "MYTH or FACT: New Orleans has always been the capital city of Louisiana.", isFact: false, explanation: "MYTH: The capital moved several times in the early years. Mobile and Biloxi both served as the capital before it was finally moved to New Orleans in 1722." },
                { question: "MYTH or FACT: The Acadians were exiled directly from France to Louisiana.", isFact: false, explanation: "MYTH: The Acadians were expelled from Acadia (modern-day Nova Scotia, Canada) by the British. After years of wandering, many found refuge in French/Spanish Louisiana." },
                { question: "MYTH or FACT: The French Code Noir granted enslaved people full rights as citizens.", isFact: false, explanation: "MYTH: The Code Noir was a harsh set of laws designed to control the enslaved population, though it did mandate Catholic instruction and forbid working on Sundays." },
                { question: "MYTH or FACT: Natchitoches is the oldest permanent European settlement in the Louisiana Purchase territory.", isFact: true, explanation: "FACT: Founded by the French in 1714 as a trade outpost, Natchitoches predates the founding of New Orleans by four years." },
                { question: "MYTH or FACT: France sold the Louisiana territory to Spain for a massive profit in 1762.", isFact: false, explanation: "MYTH: France gave Louisiana to Spain in the secret Treaty of Fontainebleau to prevent the British from taking it as a prize at the end of the French and Indian War." }
            ],
            unit4: [
                { question: "MYTH or FACT: The Declaration of Independence was fully signed by all delegates on July 4, 1776.", isFact: false, explanation: "MYTH: While the final wording was approved on July 4th, the actual signing ceremony did not begin until August 2nd." },
                { question: "MYTH or FACT: During his midnight ride, Paul Revere shouted, 'The British are coming!'", isFact: false, explanation: "MYTH: He likely shouted, 'The Regulars are coming out!' Shouting 'The British' would have made no sense, as the colonists still considered themselves British citizens." },
                { question: "MYTH or FACT: Every American colonist fiercely supported the war for independence.", isFact: false, explanation: "MYTH: The colonies were deeply divided. Historians estimate that roughly one-third were Patriots, one-third were Loyalists, and one-third remained neutral." },
                { question: "MYTH or FACT: The American colonists won the Revolutionary War entirely on their own.", isFact: false, explanation: "MYTH: Without massive financial, military, and naval support from European allies—especially France, but also Spain and the Netherlands—the Americans likely would have lost." },
                { question: "MYTH or FACT: The Proclamation of 1763 banned colonists from settling west of the Appalachian Mountains.", isFact: true, explanation: "FACT: King George III issued this proclamation to prevent costly conflicts with Native American tribes, which deeply angered colonists who felt they had fought for that land." }
            ]
        },
        grade7: {
            unit1: [
                { question: "MYTH or FACT: George Washington chopped down his father's cherry tree and confessed to it.", isFact: false, explanation: "MYTH: This famous story was completely invented by an early biographer, Parson Weems, to illustrate Washington's honesty. There is no historical evidence it happened." },
                { question: "MYTH or FACT: The Whiskey Rebellion proved the new federal government was weak and powerless.", isFact: false, explanation: "MYTH: It proved the exact opposite. By raising an army to crush the rebellion, Washington proved the new Constitutional government could enforce its laws, unlike the Articles of Confederation." },
                { question: "MYTH or FACT: Alexander Hamilton and Thomas Jefferson's disagreements led to the creation of the first political parties.", isFact: true, explanation: "FACT: Their intense conflicts over the National Bank, the economy, and federal power directly resulted in the formation of the Federalist and Democratic-Republican parties." },
                { question: "MYTH or FACT: The Alien and Sedition Acts were created to expand free speech rights.", isFact: false, explanation: "MYTH: They severely restricted free speech, allowing the government to jail newspaper editors and politicians who criticized President John Adams and the Federalist party." },
                { question: "MYTH or FACT: The Supreme Court case Marbury v. Madison established the power of judicial review.", isFact: true, explanation: "FACT: This landmark case established the Supreme Court's authority to declare laws or executive actions unconstitutional, cementing its role as a co-equal branch of government." }
            ],
            unit2: [
                { question: "MYTH or FACT: Thomas Jefferson fought a war with France to conquer the Louisiana Territory.", isFact: false, explanation: "MYTH: He purchased it peacefully. Napoleon Bonaparte, needing funds for his wars in Europe, sold the massive territory to the U.S. for $15 million in 1803." },
                { question: "MYTH or FACT: The Lewis and Clark expedition discovered a direct, all-water route to the Pacific Ocean.", isFact: false, explanation: "MYTH: While they successfully mapped the region and reached the ocean, they proved that a 'Northwest Passage' (a continuous water route) did not exist across the continent." },
                { question: "MYTH or FACT: The United States decisively won the War of 1812 and took over Canada.", isFact: false, explanation: "MYTH: The war was largely a military stalemate. The Treaty of Ghent restored all pre-war borders, though the U.S. did gain a surge of national pride and international respect." },
                { question: "MYTH or FACT: The Battle of New Orleans was fought after the peace treaty ending the war had already been signed.", isFact: true, explanation: "FACT: The Treaty of Ghent was signed in Europe weeks before the battle, but news traveled slowly across the Atlantic by ship, so the armies in Louisiana didn't know the war was over." },
                { question: "MYTH or FACT: The 'Era of Good Feelings' was a period of intense political fighting and civil war.", isFact: false, explanation: "MYTH: It was a period following the War of 1812 characterized by strong national unity and the temporary collapse of the two-party system, leaving only the Democratic-Republicans." }
            ],
            unit3: [
                { question: "MYTH or FACT: Manifest Destiny was an official law passed by Congress to force expansion.", isFact: false, explanation: "MYTH: It was not a law, but a widely held cultural belief that Americans were divinely ordained by God to settle the entire North American continent." },
                { question: "MYTH or FACT: The Trail of Tears was a voluntary migration by Native Americans seeking better land.", isFact: false, explanation: "MYTH: It was a brutal, forced relocation enacted by the U.S. government under the Indian Removal Act, resulting in the deaths of thousands of indigenous people." },
                { question: "MYTH or FACT: The invention of the cotton gin led to a decrease in the use of enslaved labor.", isFact: false, explanation: "MYTH: The cotton gin made processing cotton so incredibly profitable that plantation owners rapidly expanded their operations, drastically increasing the demand for enslaved labor." },
                { question: "MYTH or FACT: The Monroe Doctrine warned European nations against interfering in the Western Hemisphere.", isFact: true, explanation: "FACT: Issued in 1823, it declared that the Americas were off-limits to further European colonization and that the U.S. would view any interference as a hostile act." },
                { question: "MYTH or FACT: The Industrial Revolution in the U.S. began primarily in the Southern states.", isFact: false, explanation: "MYTH: It began in the North, specifically New England, where fast-moving rivers powered textile mills. The South remained heavily focused on agrarian plantation farming." }
            ],
            unit4: [
                { question: "MYTH or FACT: The Underground Railroad was a literal train system running under the soil.", isFact: false, explanation: "MYTH: It was a metaphor. It was actually a highly organized, secret network of safe houses, guides (conductors), and routes used to help enslaved people escape to freedom." },
                { question: "MYTH or FACT: The Seneca Falls Convention of 1848 immediately granted women the right to vote.", isFact: false, explanation: "MYTH: It was the launching point of the movement. Women would not secure the national right to vote until the 19th Amendment was ratified 72 years later." },
                { question: "MYTH or FACT: The Dred Scott Supreme Court decision ruled that enslaved people were property, not citizens.", isFact: true, explanation: "FACT: The 1857 ruling was a massive blow to the abolitionist movement, declaring that Black Americans had no constitutional rights and that Congress couldn't ban slavery in the territories." },
                { question: "MYTH or FACT: The Fugitive Slave Act of 1850 allowed accused runaways to testify in front of a jury.", isFact: false, explanation: "MYTH: Accused individuals were denied the right to a jury trial and could not testify. Furthermore, commissioners were paid more money to return a person to slavery than to set them free." },
                { question: "MYTH or FACT: Most people in the Northern states before the Civil War were radical abolitionists.", isFact: false, explanation: "MYTH: Radical abolitionists who wanted to end slavery immediately were a minority. Most Northerners were either indifferent or simply wanted to stop the *expansion* of slavery into new territories." }
            ]
        },
        grade8: {
            unit1: [
                { question: "MYTH or FACT: The 'Wild West' was a chaotic place where gunfights happened in the streets every day.", isFact: false, explanation: "MYTH: While violence occurred, most frontier towns strictly enforced gun control laws to maintain order. The Hollywood image of daily 'high noon' shootouts is highly exaggerated." },
                { question: "MYTH or FACT: The 'Exodusters' were African Americans who migrated to Kansas to escape the Jim Crow South.", isFact: true, explanation: "FACT: In the late 1870s, thousands of African Americans fled the violence and economic oppression of the post-Reconstruction South to seek land and freedom on the plains." },
                { question: "MYTH or FACT: The Supreme Court's ruling in Plessy v. Ferguson ensured that segregated facilities were truly equal.", isFact: false, explanation: "MYTH: The 'separate but equal' doctrine provided legal cover for systemic racism. In reality, facilities for Black Americans were almost universally underfunded and inferior." },
                { question: "MYTH or FACT: Booker T. Washington and W.E.B. Du Bois agreed entirely on the strategy for achieving civil rights.", isFact: false, explanation: "MYTH: They deeply disagreed. Washington advocated for gradual economic self-reliance (the 'Atlanta Compromise'), while Du Bois demanded immediate political equality and founded the NAACP." },
                { question: "MYTH or FACT: The U.S. government actively encouraged the slaughter of the American buffalo.", isFact: true, explanation: "FACT: Officials recognized that the Plains Indians depended entirely on the buffalo. Exterminating the herds was a calculated strategy to force tribes onto reservations." }
            ],
            unit2: [
                { question: "MYTH or FACT: Laissez-faire government policies helped prevent the rise of corporate monopolies.", isFact: false, explanation: "MYTH: 'Laissez-faire' means 'hands off'. Because the government refused to regulate businesses, powerful industrialists were able to ruthlessly crush competition and form massive monopolies." },
                { question: "MYTH or FACT: Muckraking journalists played a major role in exposing corruption and bringing about Progressive reforms.", isFact: true, explanation: "FACT: Investigative writers like Upton Sinclair and Ida Tarbell shocked the public with their findings, leading directly to laws like the Meat Inspection Act and anti-trust enforcement." },
                { question: "MYTH or FACT: Immigrants arriving in the late 1800s easily found safe, high-paying jobs in factories.", isFact: false, explanation: "MYTH: Most immigrants faced brutal working conditions, extremely long hours, low wages, and dangerous environments. Child labor was also rampant due to deep poverty." },
                { question: "MYTH or FACT: Horizontal integration involves buying out all competing companies in the same industry.", isFact: true, explanation: "FACT: This strategy, famously used by John D. Rockefeller's Standard Oil, allows a company to eliminate competition and control the market price of a product." },
                { question: "MYTH or FACT: The Populist Party was formed by wealthy bankers to protect their profits.", isFact: false, explanation: "MYTH: The Populist (or People's) Party was a grassroots movement formed by desperate farmers and laborers fighting against the power of banks, railroads, and big business." }
            ],
            unit3: [
                { question: "MYTH or FACT: The United States joined the League of Nations to help prevent future global wars.", isFact: false, explanation: "MYTH: Despite President Woodrow Wilson being the chief architect of the League, the U.S. Senate refused to ratify the treaty, fearing it would drag the country into foreign conflicts." },
                { question: "MYTH or FACT: 'Yellow Journalism' played a major role in pushing the U.S. into the Spanish-American War.", isFact: true, explanation: "FACT: Newspaper publishers sensationalized stories, particularly the explosion of the USS Maine, to inflame public anger and boost sales, highly influencing the push for war." },
                { question: "MYTH or FACT: The Zimmermann Telegram was a German proposal of alliance to Mexico against the U.S.", isFact: true, explanation: "FACT: Germany promised to help Mexico recover lost territory (like Texas) if they attacked the U.S. Its interception and publication outraged the American public." },
                { question: "MYTH or FACT: The 19th Amendment guaranteeing women the right to vote was passed without any opposition.", isFact: false, explanation: "MYTH: The suffrage movement fought a grueling, decades-long battle. Activists faced public mockery, arrest, physical violence, and force-feeding in prison before winning the vote in 1920." },
                { question: "MYTH or FACT: Trench warfare on the Western Front led to quick, decisive military victories in WWI.", isFact: false, explanation: "MYTH: Trench warfare resulted in a brutal, years-long stalemate. The defensive advantage of machine guns and barbed wire made advancing across 'No Man's Land' nearly impossible and deadly." }
            ],
            unit4: [
                { question: "MYTH or FACT: Prohibition successfully stopped all alcohol consumption in the United States.", isFact: false, explanation: "MYTH: While legal sales stopped, it fueled a massive black market. People drank in illegal 'speakeasies,' and it led to the rapid rise of violent organized crime syndicates." },
                { question: "MYTH or FACT: Buying stocks 'on margin' was a safe, risk-free way to invest in the 1920s.", isFact: false, explanation: "MYTH: It was incredibly reckless. Buying on margin meant borrowing money to buy stocks. When the market crashed, investors lost everything and couldn't repay their massive loans." },
                { question: "MYTH or FACT: The Dust Bowl was an environmental disaster worsened by poor farming practices.", isFact: true, explanation: "FACT: While a severe drought was the trigger, decades of deep plowing had destroyed the native prairie grasses. Without roots to hold the soil, the wind blew it away in massive dust storms." },
                { question: "MYTH or FACT: The New Deal ended the Great Depression immediately within its first year.", isFact: false, explanation: "MYTH: While the New Deal provided vital relief and reformed the banking system, unemployment remained high for years. The massive industrial production required for WWII ultimately ended the Depression." },
                { question: "MYTH or FACT: Huey Long was a popular Louisiana politician because he advocated for heavily taxing the rich.", isFact: true, explanation: "FACT: His populist 'Share Our Wealth' program appealed strongly to poor and working-class citizens during the Depression by promising to redistribute wealth from corporations and the elite." }
            ]
        }
    }
};